// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID                pgtype.UUID        `json:"id"`
	GameIntegrationID pgtype.UUID        `json:"game_integration_id"`
	Slug              string             `json:"slug"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	StoragePath       string             `json:"storage_path"`
	Version           string             `json:"version"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
