// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Counts all games including inactive
	CountAllGames(ctx context.Context) (int64, error)
	// Counts total active games
	CountGames(ctx context.Context) (int64, error)
	// ============================================================================
	// GAME QUERIES
	// Generated code will be used by internal/repository/game.go
	// ============================================================================
	// Creates a new game and returns the created record
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	// Soft delete - sets is_active to false
	DeleteGame(ctx context.Context, id pgtype.UUID) error
	// Checks if a game exists
	GameExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// Checks if a slug is already taken
	GameSlugExists(ctx context.Context, slug string) (bool, error)
	// Retrieves a game by its ID
	GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error)
	// Retrieves an active game by its game integration ID
	GetGameByIntegrationID(ctx context.Context, gameIntegrationID pgtype.UUID) (Game, error)
	// Retrieves an active game by its slug
	GetGameBySlug(ctx context.Context, slug string) (Game, error)
	// Hard delete - permanently removes game (use with caution)
	HardDeleteGame(ctx context.Context, id pgtype.UUID) error
	// Lists all games including inactive ones (admin use)
	ListAllGames(ctx context.Context) ([]Game, error)
	// Lists all active games ordered by name
	ListGames(ctx context.Context) ([]Game, error)
	// Updates a game's information using optional parameters
	UpdateGame(ctx context.Context, arg UpdateGameParams) error
}

var _ Querier = (*Queries)(nil)
