// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllGames = `-- name: CountAllGames :one
SELECT COUNT(*) FROM games
`

// Counts all games including inactive
func (q *Queries) CountAllGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGames = `-- name: CountGames :one
SELECT COUNT(*) FROM games WHERE is_active = true
`

// Counts total active games
func (q *Queries) CountGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (
    game_integration_id,
    slug,
    name,
    description,
    logo_url,
    storage_path,
    version
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, game_integration_id, slug, name, description, logo_url, storage_path, version, is_active, created_at, updated_at
`

type CreateGameParams struct {
	GameIntegrationID pgtype.UUID `json:"game_integration_id"`
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	StoragePath       string      `json:"storage_path"`
	Version           string      `json:"version"`
}

// ============================================================================
// GAME QUERIES
// Generated code will be used by internal/repository/game.go
// ============================================================================
// Creates a new game and returns the created record
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.GameIntegrationID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.StoragePath,
		arg.Version,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameIntegrationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.StoragePath,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
UPDATE games
SET
    is_active = false,
    updated_at = NOW()
WHERE id = $1
`

// Soft delete - sets is_active to false
func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const gameExists = `-- name: GameExists :one
SELECT EXISTS(
    SELECT 1 FROM games WHERE id = $1
) AS exists
`

// Checks if a game exists
func (q *Queries) GameExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, gameExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const gameSlugExists = `-- name: GameSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM games WHERE slug = $1 AND is_active = true
) AS exists
`

// Checks if a slug is already taken
func (q *Queries) GameSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, gameSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, game_integration_id, slug, name, description, logo_url, storage_path, version, is_active, created_at, updated_at
FROM games
WHERE id = $1
`

// Retrieves a game by its ID
func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameIntegrationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.StoragePath,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameByIntegrationID = `-- name: GetGameByIntegrationID :one
SELECT id, game_integration_id, slug, name, description, logo_url, storage_path, version, is_active, created_at, updated_at
FROM games
WHERE game_integration_id = $1 AND is_active = true
`

// Retrieves an active game by its game integration ID
func (q *Queries) GetGameByIntegrationID(ctx context.Context, gameIntegrationID pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByIntegrationID, gameIntegrationID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameIntegrationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.StoragePath,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameBySlug = `-- name: GetGameBySlug :one
SELECT id, game_integration_id, slug, name, description, logo_url, storage_path, version, is_active, created_at, updated_at
FROM games
WHERE slug = $1 AND is_active = true
`

// Retrieves an active game by its slug
func (q *Queries) GetGameBySlug(ctx context.Context, slug string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameBySlug, slug)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameIntegrationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.StoragePath,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteGame = `-- name: HardDeleteGame :exec
DELETE FROM games WHERE id = $1
`

// Hard delete - permanently removes game (use with caution)
func (q *Queries) HardDeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteGame, id)
	return err
}

const listAllGames = `-- name: ListAllGames :many
SELECT id, game_integration_id, slug, name, description, logo_url, storage_path, version, is_active, created_at, updated_at
FROM games
ORDER BY name ASC
`

// Lists all games including inactive ones (admin use)
func (q *Queries) ListAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.GameIntegrationID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.StoragePath,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id, game_integration_id, slug, name, description, logo_url, storage_path, version, is_active, created_at, updated_at
FROM games
WHERE is_active = true
ORDER BY name ASC
`

// Lists all active games ordered by name
func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.GameIntegrationID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.StoragePath,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games
SET
    game_integration_id = COALESCE($2, game_integration_id),
    slug = COALESCE($3, slug),
    name = COALESCE($4, name),
    description = COALESCE($5, description),
    logo_url = COALESCE($6, logo_url),
    storage_path = COALESCE($7, storage_path),
    version = COALESCE($8, version),
    is_active = COALESCE($9, is_active),
    updated_at = NOW()
WHERE id = $1
`

type UpdateGameParams struct {
	ID                pgtype.UUID `json:"id"`
	GameIntegrationID pgtype.UUID `json:"game_integration_id"`
	Slug              pgtype.Text `json:"slug"`
	Name              pgtype.Text `json:"name"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	StoragePath       pgtype.Text `json:"storage_path"`
	Version           pgtype.Text `json:"version"`
	IsActive          pgtype.Bool `json:"is_active"`
}

// Updates a game's information using optional parameters
func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.Exec(ctx, updateGame,
		arg.ID,
		arg.GameIntegrationID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.StoragePath,
		arg.Version,
		arg.IsActive,
	)
	return err
}
