// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (
    slug,
    name,
    description,
    logo_url,
    s3_path,
    version,
    versioning_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, slug, name, description, logo_url, s3_path, version, versioning_enabled, is_active, created_at, updated_at
`

type CreateGameParams struct {
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	S3Path            string      `json:"s3_path"`
	Version           string      `json:"version"`
	VersioningEnabled bool        `json:"versioning_enabled"`
}

// Creates a new game record
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.S3Path,
		arg.Version,
		arg.VersioningEnabled,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.S3Path,
		&i.Version,
		&i.VersioningEnabled,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
UPDATE games
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

// Soft deletes a game (sets is_active to false)
func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, slug, name, description, logo_url, s3_path, version, versioning_enabled, is_active, created_at, updated_at
FROM games
WHERE id = $1
`

// Retrieves a game by its ID
func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.S3Path,
		&i.Version,
		&i.VersioningEnabled,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameBySlug = `-- name: GetGameBySlug :one
SELECT id, slug, name, description, logo_url, s3_path, version, versioning_enabled, is_active, created_at, updated_at
FROM games
WHERE slug = $1 AND is_active = true
`

// Retrieves an active game by its slug
func (q *Queries) GetGameBySlug(ctx context.Context, slug string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameBySlug, slug)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.S3Path,
		&i.Version,
		&i.VersioningEnabled,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteGame = `-- name: HardDeleteGame :exec
DELETE FROM games
WHERE id = $1
`

// Permanently deletes a game
func (q *Queries) HardDeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteGame, id)
	return err
}

const listAllGames = `-- name: ListAllGames :many
SELECT id, slug, name, description, logo_url, s3_path, version, versioning_enabled, is_active, created_at, updated_at
FROM games
ORDER BY created_at DESC
`

// Lists all games (including inactive)
func (q *Queries) ListAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.S3Path,
			&i.Version,
			&i.VersioningEnabled,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id, slug, name, description, logo_url, s3_path, version, versioning_enabled, is_active, created_at, updated_at
FROM games
WHERE is_active = true
ORDER BY created_at DESC
`

// Lists all active games
func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.S3Path,
			&i.Version,
			&i.VersioningEnabled,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games
SET
    slug = COALESCE($1, slug),
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    logo_url = COALESCE($4, logo_url),
    s3_path = COALESCE($5, s3_path),
    version = COALESCE($6, version),
    versioning_enabled = COALESCE($7, versioning_enabled),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $9
`

type UpdateGameParams struct {
	Slug              pgtype.Text `json:"slug"`
	Name              pgtype.Text `json:"name"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	S3Path            pgtype.Text `json:"s3_path"`
	Version           pgtype.Text `json:"version"`
	VersioningEnabled pgtype.Bool `json:"versioning_enabled"`
	IsActive          pgtype.Bool `json:"is_active"`
	ID                pgtype.UUID `json:"id"`
}

// Updates a game record
func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.Exec(ctx, updateGame,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.S3Path,
		arg.Version,
		arg.VersioningEnabled,
		arg.IsActive,
		arg.ID,
	)
	return err
}
