// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Creates a new game record
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	// Soft deletes a game (sets is_active to false)
	DeleteGame(ctx context.Context, id pgtype.UUID) error
	// Retrieves a game by its ID
	GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error)
	// Retrieves an active game by its slug
	GetGameBySlug(ctx context.Context, slug string) (Game, error)
	// Permanently deletes a game
	HardDeleteGame(ctx context.Context, id pgtype.UUID) error
	// Lists all games (including inactive)
	ListAllGames(ctx context.Context) ([]Game, error)
	// Lists all active games
	ListGames(ctx context.Context) ([]Game, error)
	// Updates a game record
	UpdateGame(ctx context.Context, arg UpdateGameParams) error
}

var _ Querier = (*Queries)(nil)
