// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bracket_queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateBracket = `-- name: CreateBracket :one

INSERT INTO tournament_brackets (
    tournament_id,
    total_rounds,
    total_matches,
    byes_count,
    generated_at
) VALUES (
    $1, $2, $3, $4, NOW()
) RETURNING id, tournament_id, total_rounds, total_matches, byes_count, generated_at
`

type CreateBracketParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	TotalRounds  int32       `json:"total_rounds"`
	TotalMatches int32       `json:"total_matches"`
	ByesCount    int32       `json:"byes_count"`
}

// ============================================================================
// Bracket Queries
// ============================================================================
func (q *Queries) CreateBracket(ctx context.Context, arg CreateBracketParams) (TournamentBracket, error) {
	row := q.db.QueryRow(ctx, CreateBracket,
		arg.TournamentID,
		arg.TotalRounds,
		arg.TotalMatches,
		arg.ByesCount,
	)
	var i TournamentBracket
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.TotalRounds,
		&i.TotalMatches,
		&i.ByesCount,
		&i.GeneratedAt,
	)
	return i, err
}

const DeleteBracket = `-- name: DeleteBracket :exec
DELETE FROM tournament_brackets
WHERE id = $1
`

func (q *Queries) DeleteBracket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteBracket, id)
	return err
}

const GetBracketByID = `-- name: GetBracketByID :one
SELECT id, tournament_id, total_rounds, total_matches, byes_count, generated_at FROM tournament_brackets
WHERE id = $1
`

func (q *Queries) GetBracketByID(ctx context.Context, id pgtype.UUID) (TournamentBracket, error) {
	row := q.db.QueryRow(ctx, GetBracketByID, id)
	var i TournamentBracket
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.TotalRounds,
		&i.TotalMatches,
		&i.ByesCount,
		&i.GeneratedAt,
	)
	return i, err
}

const GetBracketByTournamentID = `-- name: GetBracketByTournamentID :one
SELECT id, tournament_id, total_rounds, total_matches, byes_count, generated_at FROM tournament_brackets
WHERE tournament_id = $1
`

func (q *Queries) GetBracketByTournamentID(ctx context.Context, tournamentID pgtype.UUID) (TournamentBracket, error) {
	row := q.db.QueryRow(ctx, GetBracketByTournamentID, tournamentID)
	var i TournamentBracket
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.TotalRounds,
		&i.TotalMatches,
		&i.ByesCount,
		&i.GeneratedAt,
	)
	return i, err
}

const GetBracketWithRoundsAndMatches = `-- name: GetBracketWithRoundsAndMatches :many
SELECT 
    b.id as bracket_id,
    b.tournament_id,
    b.total_rounds as bracket_total_rounds,
    b.total_matches as bracket_total_matches,
    b.byes_count,
    b.generated_at as bracket_generated_at,
    r.id as round_id,
    r.round_number,
    r.round_name,
    r.matches_count as round_matches_count,
    r.status as round_status,
    r.started_at as round_started_at,
    r.completed_at as round_completed_at,
    m.id as match_id,
    m.match_number,
    m.participant1_id,
    m.participant2_id,
    m.status as match_status,
    m.participant1_ready,
    m.participant2_ready,
    m.winner_id,
    m.score_player1,
    m.score_player2,
    m.result_source,
    m.next_match_id,
    m.created_at as match_created_at,
    m.started_at as match_started_at,
    m.completed_at as match_completed_at
FROM tournament_brackets b
LEFT JOIN tournament_rounds r ON r.bracket_id = b.id
LEFT JOIN tournament_matches m ON m.round_id = r.id
WHERE b.tournament_id = $1
ORDER BY r.round_number ASC, m.match_number ASC
`

type GetBracketWithRoundsAndMatchesRow struct {
	BracketID           pgtype.UUID      `json:"bracket_id"`
	TournamentID        pgtype.UUID      `json:"tournament_id"`
	BracketTotalRounds  int32            `json:"bracket_total_rounds"`
	BracketTotalMatches int32            `json:"bracket_total_matches"`
	ByesCount           int32            `json:"byes_count"`
	BracketGeneratedAt  time.Time        `json:"bracket_generated_at"`
	RoundID             pgtype.UUID      `json:"round_id"`
	RoundNumber         pgtype.Int4      `json:"round_number"`
	RoundName           pgtype.Text      `json:"round_name"`
	RoundMatchesCount   pgtype.Int4      `json:"round_matches_count"`
	RoundStatus         pgtype.Text      `json:"round_status"`
	RoundStartedAt      pgtype.Timestamp `json:"round_started_at"`
	RoundCompletedAt    pgtype.Timestamp `json:"round_completed_at"`
	MatchID             pgtype.UUID      `json:"match_id"`
	MatchNumber         pgtype.Int4      `json:"match_number"`
	Participant1ID      pgtype.UUID      `json:"participant1_id"`
	Participant2ID      pgtype.UUID      `json:"participant2_id"`
	MatchStatus         pgtype.Text      `json:"match_status"`
	Participant1Ready   pgtype.Bool      `json:"participant1_ready"`
	Participant2Ready   pgtype.Bool      `json:"participant2_ready"`
	WinnerID            pgtype.UUID      `json:"winner_id"`
	ScorePlayer1        pgtype.Int4      `json:"score_player1"`
	ScorePlayer2        pgtype.Int4      `json:"score_player2"`
	ResultSource        pgtype.Text      `json:"result_source"`
	NextMatchID         pgtype.UUID      `json:"next_match_id"`
	MatchCreatedAt      pgtype.Timestamp `json:"match_created_at"`
	MatchStartedAt      pgtype.Timestamp `json:"match_started_at"`
	MatchCompletedAt    pgtype.Timestamp `json:"match_completed_at"`
}

// Complex join query for bracket visualization
func (q *Queries) GetBracketWithRoundsAndMatches(ctx context.Context, tournamentID pgtype.UUID) ([]GetBracketWithRoundsAndMatchesRow, error) {
	rows, err := q.db.Query(ctx, GetBracketWithRoundsAndMatches, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBracketWithRoundsAndMatchesRow{}
	for rows.Next() {
		var i GetBracketWithRoundsAndMatchesRow
		if err := rows.Scan(
			&i.BracketID,
			&i.TournamentID,
			&i.BracketTotalRounds,
			&i.BracketTotalMatches,
			&i.ByesCount,
			&i.BracketGeneratedAt,
			&i.RoundID,
			&i.RoundNumber,
			&i.RoundName,
			&i.RoundMatchesCount,
			&i.RoundStatus,
			&i.RoundStartedAt,
			&i.RoundCompletedAt,
			&i.MatchID,
			&i.MatchNumber,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.MatchStatus,
			&i.Participant1Ready,
			&i.Participant2Ready,
			&i.WinnerID,
			&i.ScorePlayer1,
			&i.ScorePlayer2,
			&i.ResultSource,
			&i.NextMatchID,
			&i.MatchCreatedAt,
			&i.MatchStartedAt,
			&i.MatchCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
