// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AssignWinnerToNextMatch = `-- name: AssignWinnerToNextMatch :exec
UPDATE tournament_matches
SET 
    participant1_id = CASE 
        WHEN participant1_id IS NULL THEN $2 
        ELSE participant1_id 
    END,
    participant2_id = CASE 
        WHEN participant1_id IS NOT NULL AND participant2_id IS NULL THEN $2 
        ELSE participant2_id 
    END,
    updated_at = NOW()
WHERE id = $1
`

type AssignWinnerToNextMatchParams struct {
	ID             pgtype.UUID `json:"id"`
	Participant1ID pgtype.UUID `json:"participant1_id"`
}

// Assign winner to next match's participant slot
func (q *Queries) AssignWinnerToNextMatch(ctx context.Context, arg AssignWinnerToNextMatchParams) error {
	_, err := q.db.Exec(ctx, AssignWinnerToNextMatch, arg.ID, arg.Participant1ID)
	return err
}

const ClearDisconnectedPlayerInfo = `-- name: ClearDisconnectedPlayerInfo :exec
UPDATE tournament_matches
SET disconnected_player_id = NULL, disconnected_at = NULL, updated_at = NOW()
WHERE id = $1
`

// Clear disconnected player info
func (q *Queries) ClearDisconnectedPlayerInfo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ClearDisconnectedPlayerInfo, id)
	return err
}

const ClearMatchDisconnect = `-- name: ClearMatchDisconnect :exec
UPDATE tournament_matches
SET 
    disconnected_player_id = NULL,
    disconnected_at = NULL,
    status = 'started',
    updated_at = NOW()
WHERE id = $1
`

// Clear disconnect tracking when player reconnects
func (q *Queries) ClearMatchDisconnect(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ClearMatchDisconnect, id)
	return err
}

const CreateMatch = `-- name: CreateMatch :one

INSERT INTO tournament_matches (
    id,
    round_id,
    match_number,
    next_match_id,
    participant1_id,
    participant2_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, round_id, match_number, next_match_id, participant1_id, participant2_id, status, participant1_ready, participant2_ready, winner_id, score_player1, score_player2, result_source, disconnected_player_id, disconnected_at, game_api_match_id, game_api_poll_attempts, game_api_last_poll, created_at, started_at, completed_at, updated_at
`

type CreateMatchParams struct {
	ID             pgtype.UUID `json:"id"`
	RoundID        pgtype.UUID `json:"round_id"`
	MatchNumber    int32       `json:"match_number"`
	NextMatchID    pgtype.UUID `json:"next_match_id"`
	Participant1ID pgtype.UUID `json:"participant1_id"`
	Participant2ID pgtype.UUID `json:"participant2_id"`
	Status         string      `json:"status"`
}

// ============================================================================
// Match Queries
// ============================================================================
func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (TournamentMatch, error) {
	row := q.db.QueryRow(ctx, CreateMatch,
		arg.ID,
		arg.RoundID,
		arg.MatchNumber,
		arg.NextMatchID,
		arg.Participant1ID,
		arg.Participant2ID,
		arg.Status,
	)
	var i TournamentMatch
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.MatchNumber,
		&i.NextMatchID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.Status,
		&i.Participant1Ready,
		&i.Participant2Ready,
		&i.WinnerID,
		&i.ScorePlayer1,
		&i.ScorePlayer2,
		&i.ResultSource,
		&i.DisconnectedPlayerID,
		&i.DisconnectedAt,
		&i.GameApiMatchID,
		&i.GameApiPollAttempts,
		&i.GameApiLastPoll,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetFinalMatch = `-- name: GetFinalMatch :one
SELECT id, round_id, match_number, next_match_id, participant1_id, participant2_id, status, participant1_ready, participant2_ready, winner_id, score_player1, score_player2, result_source, disconnected_player_id, disconnected_at, game_api_match_id, game_api_poll_attempts, game_api_last_poll, created_at, started_at, completed_at, updated_at FROM tournament_matches
WHERE round_id IN (
    SELECT id FROM tournament_rounds WHERE bracket_id = (
        SELECT id FROM tournament_brackets WHERE tournament_id = $1
    )
)
AND next_match_id IS NULL
`

// Get the final match (next_match_id IS NULL)
func (q *Queries) GetFinalMatch(ctx context.Context, tournamentID pgtype.UUID) (TournamentMatch, error) {
	row := q.db.QueryRow(ctx, GetFinalMatch, tournamentID)
	var i TournamentMatch
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.MatchNumber,
		&i.NextMatchID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.Status,
		&i.Participant1Ready,
		&i.Participant2Ready,
		&i.WinnerID,
		&i.ScorePlayer1,
		&i.ScorePlayer2,
		&i.ResultSource,
		&i.DisconnectedPlayerID,
		&i.DisconnectedAt,
		&i.GameApiMatchID,
		&i.GameApiPollAttempts,
		&i.GameApiLastPoll,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMatchByID = `-- name: GetMatchByID :one
SELECT id, round_id, match_number, next_match_id, participant1_id, participant2_id, status, participant1_ready, participant2_ready, winner_id, score_player1, score_player2, result_source, disconnected_player_id, disconnected_at, game_api_match_id, game_api_poll_attempts, game_api_last_poll, created_at, started_at, completed_at, updated_at FROM tournament_matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (TournamentMatch, error) {
	row := q.db.QueryRow(ctx, GetMatchByID, id)
	var i TournamentMatch
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.MatchNumber,
		&i.NextMatchID,
		&i.Participant1ID,
		&i.Participant2ID,
		&i.Status,
		&i.Participant1Ready,
		&i.Participant2Ready,
		&i.WinnerID,
		&i.ScorePlayer1,
		&i.ScorePlayer2,
		&i.ResultSource,
		&i.DisconnectedPlayerID,
		&i.DisconnectedAt,
		&i.GameApiMatchID,
		&i.GameApiPollAttempts,
		&i.GameApiLastPoll,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMatchesByRoundID = `-- name: GetMatchesByRoundID :many
SELECT id, round_id, match_number, next_match_id, participant1_id, participant2_id, status, participant1_ready, participant2_ready, winner_id, score_player1, score_player2, result_source, disconnected_player_id, disconnected_at, game_api_match_id, game_api_poll_attempts, game_api_last_poll, created_at, started_at, completed_at, updated_at FROM tournament_matches
WHERE round_id = $1
ORDER BY match_number ASC
`

func (q *Queries) GetMatchesByRoundID(ctx context.Context, roundID pgtype.UUID) ([]TournamentMatch, error) {
	rows, err := q.db.Query(ctx, GetMatchesByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentMatch{}
	for rows.Next() {
		var i TournamentMatch
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.MatchNumber,
			&i.NextMatchID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.Status,
			&i.Participant1Ready,
			&i.Participant2Ready,
			&i.WinnerID,
			&i.ScorePlayer1,
			&i.ScorePlayer2,
			&i.ResultSource,
			&i.DisconnectedPlayerID,
			&i.DisconnectedAt,
			&i.GameApiMatchID,
			&i.GameApiPollAttempts,
			&i.GameApiLastPoll,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMatchesByTournamentAndRound = `-- name: GetMatchesByTournamentAndRound :many
SELECT m.id, m.round_id, m.match_number, m.next_match_id, m.participant1_id, m.participant2_id, m.status, m.participant1_ready, m.participant2_ready, m.winner_id, m.score_player1, m.score_player2, m.result_source, m.disconnected_player_id, m.disconnected_at, m.game_api_match_id, m.game_api_poll_attempts, m.game_api_last_poll, m.created_at, m.started_at, m.completed_at, m.updated_at FROM tournament_matches m
JOIN tournament_rounds r ON m.round_id = r.id
JOIN tournament_brackets b ON r.bracket_id = b.id
WHERE b.tournament_id = $1 AND r.round_number = $2
ORDER BY m.match_number ASC
`

type GetMatchesByTournamentAndRoundParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	RoundNumber  int32       `json:"round_number"`
}

// Get all matches for a specific tournament and round number
func (q *Queries) GetMatchesByTournamentAndRound(ctx context.Context, arg GetMatchesByTournamentAndRoundParams) ([]TournamentMatch, error) {
	rows, err := q.db.Query(ctx, GetMatchesByTournamentAndRound, arg.TournamentID, arg.RoundNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentMatch{}
	for rows.Next() {
		var i TournamentMatch
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.MatchNumber,
			&i.NextMatchID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.Status,
			&i.Participant1Ready,
			&i.Participant2Ready,
			&i.WinnerID,
			&i.ScorePlayer1,
			&i.ScorePlayer2,
			&i.ResultSource,
			&i.DisconnectedPlayerID,
			&i.DisconnectedAt,
			&i.GameApiMatchID,
			&i.GameApiPollAttempts,
			&i.GameApiLastPoll,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMatchesForGameAPIPolling = `-- name: GetMatchesForGameAPIPolling :many
SELECT id, round_id, match_number, next_match_id, participant1_id, participant2_id, status, participant1_ready, participant2_ready, winner_id, score_player1, score_player2, result_source, disconnected_player_id, disconnected_at, game_api_match_id, game_api_poll_attempts, game_api_last_poll, created_at, started_at, completed_at, updated_at FROM tournament_matches
WHERE status = 'started'
  AND game_api_match_id IS NOT NULL
  AND result_source IS NULL
  AND (game_api_last_poll IS NULL OR game_api_last_poll < NOW() - INTERVAL '5 seconds')
ORDER BY game_api_last_poll ASC NULLS FIRST
LIMIT $1
`

// Get matches that need Game API polling
func (q *Queries) GetMatchesForGameAPIPolling(ctx context.Context, limit int32) ([]TournamentMatch, error) {
	rows, err := q.db.Query(ctx, GetMatchesForGameAPIPolling, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentMatch{}
	for rows.Next() {
		var i TournamentMatch
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.MatchNumber,
			&i.NextMatchID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.Status,
			&i.Participant1Ready,
			&i.Participant2Ready,
			&i.WinnerID,
			&i.ScorePlayer1,
			&i.ScorePlayer2,
			&i.ResultSource,
			&i.DisconnectedPlayerID,
			&i.DisconnectedAt,
			&i.GameApiMatchID,
			&i.GameApiPollAttempts,
			&i.GameApiLastPoll,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMatchesForPlayer = `-- name: GetMatchesForPlayer :many
SELECT id, round_id, match_number, next_match_id, participant1_id, participant2_id, status, participant1_ready, participant2_ready, winner_id, score_player1, score_player2, result_source, disconnected_player_id, disconnected_at, game_api_match_id, game_api_poll_attempts, game_api_last_poll, created_at, started_at, completed_at, updated_at FROM tournament_matches
WHERE (participant1_id = $1 OR participant2_id = $1)
  AND status IN ('pending', 'ready', 'started', 'paused')
ORDER BY created_at DESC
`

// Get all matches for a specific player (participant1 or participant2)
func (q *Queries) GetMatchesForPlayer(ctx context.Context, participant1ID pgtype.UUID) ([]TournamentMatch, error) {
	rows, err := q.db.Query(ctx, GetMatchesForPlayer, participant1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentMatch{}
	for rows.Next() {
		var i TournamentMatch
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.MatchNumber,
			&i.NextMatchID,
			&i.Participant1ID,
			&i.Participant2ID,
			&i.Status,
			&i.Participant1Ready,
			&i.Participant2Ready,
			&i.WinnerID,
			&i.ScorePlayer1,
			&i.ScorePlayer2,
			&i.ResultSource,
			&i.DisconnectedPlayerID,
			&i.DisconnectedAt,
			&i.GameApiMatchID,
			&i.GameApiPollAttempts,
			&i.GameApiLastPoll,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDisconnectedPlayerOnly = `-- name: UpdateDisconnectedPlayerOnly :exec
UPDATE tournament_matches
SET disconnected_player_id = $2, disconnected_at = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateDisconnectedPlayerOnlyParams struct {
	ID                   pgtype.UUID      `json:"id"`
	DisconnectedPlayerID pgtype.UUID      `json:"disconnected_player_id"`
	DisconnectedAt       pgtype.Timestamp `json:"disconnected_at"`
}

// Update disconnected player info without changing status
func (q *Queries) UpdateDisconnectedPlayerOnly(ctx context.Context, arg UpdateDisconnectedPlayerOnlyParams) error {
	_, err := q.db.Exec(ctx, UpdateDisconnectedPlayerOnly, arg.ID, arg.DisconnectedPlayerID, arg.DisconnectedAt)
	return err
}

const UpdateMatchDisconnect = `-- name: UpdateMatchDisconnect :exec
UPDATE tournament_matches
SET 
    disconnected_player_id = $2,
    disconnected_at = $3,
    status = 'paused',
    updated_at = NOW()
WHERE id = $1
`

type UpdateMatchDisconnectParams struct {
	ID                   pgtype.UUID      `json:"id"`
	DisconnectedPlayerID pgtype.UUID      `json:"disconnected_player_id"`
	DisconnectedAt       pgtype.Timestamp `json:"disconnected_at"`
}

// Track player disconnect for CS:GO-style handling
func (q *Queries) UpdateMatchDisconnect(ctx context.Context, arg UpdateMatchDisconnectParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchDisconnect, arg.ID, arg.DisconnectedPlayerID, arg.DisconnectedAt)
	return err
}

const UpdateMatchGameAPIInfo = `-- name: UpdateMatchGameAPIInfo :exec
UPDATE tournament_matches
SET 
    game_api_match_id = $2,
    game_api_poll_attempts = $3,
    game_api_last_poll = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMatchGameAPIInfoParams struct {
	ID                  pgtype.UUID      `json:"id"`
	GameApiMatchID      pgtype.Text      `json:"game_api_match_id"`
	GameApiPollAttempts pgtype.Int4      `json:"game_api_poll_attempts"`
	GameApiLastPoll     pgtype.Timestamp `json:"game_api_last_poll"`
}

// Track Game API polling attempts
func (q *Queries) UpdateMatchGameAPIInfo(ctx context.Context, arg UpdateMatchGameAPIInfoParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchGameAPIInfo,
		arg.ID,
		arg.GameApiMatchID,
		arg.GameApiPollAttempts,
		arg.GameApiLastPoll,
	)
	return err
}

const UpdateMatchReady = `-- name: UpdateMatchReady :exec
UPDATE tournament_matches
SET 
    participant1_ready = CASE 
        WHEN participant1_id = $2 THEN $3 
        ELSE participant1_ready 
    END,
    participant2_ready = CASE 
        WHEN participant2_id = $2 THEN $3 
        ELSE participant2_ready 
    END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMatchReadyParams struct {
	ID                pgtype.UUID `json:"id"`
	Participant1ID    pgtype.UUID `json:"participant1_id"`
	Participant1Ready bool        `json:"participant1_ready"`
}

// Update ready status for a specific participant
func (q *Queries) UpdateMatchReady(ctx context.Context, arg UpdateMatchReadyParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchReady, arg.ID, arg.Participant1ID, arg.Participant1Ready)
	return err
}

const UpdateMatchResult = `-- name: UpdateMatchResult :exec
UPDATE tournament_matches
SET 
    winner_id = $2,
    score_player1 = $3,
    score_player2 = $4,
    result_source = $5,
    status = 'completed',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateMatchResultParams struct {
	ID           pgtype.UUID `json:"id"`
	WinnerID     pgtype.UUID `json:"winner_id"`
	ScorePlayer1 pgtype.Int4 `json:"score_player1"`
	ScorePlayer2 pgtype.Int4 `json:"score_player2"`
	ResultSource pgtype.Text `json:"result_source"`
}

func (q *Queries) UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchResult,
		arg.ID,
		arg.WinnerID,
		arg.ScorePlayer1,
		arg.ScorePlayer2,
		arg.ResultSource,
	)
	return err
}

const UpdateMatchScore = `-- name: UpdateMatchScore :exec
UPDATE tournament_matches
SET 
    score_player1 = $2,
    score_player2 = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMatchScoreParams struct {
	ID           pgtype.UUID `json:"id"`
	ScorePlayer1 pgtype.Int4 `json:"score_player1"`
	ScorePlayer2 pgtype.Int4 `json:"score_player2"`
}

// Update scores during match (for disconnect point adjustments)
func (q *Queries) UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchScore, arg.ID, arg.ScorePlayer1, arg.ScorePlayer2)
	return err
}

const UpdateMatchStatus = `-- name: UpdateMatchStatus :exec
UPDATE tournament_matches
SET 
    status = $2,
    updated_at = NOW(),
    started_at = CASE 
        WHEN $2 = 'started' AND started_at IS NULL THEN NOW() 
        ELSE started_at 
    END,
    completed_at = CASE 
        WHEN $2 = 'completed' THEN NOW() 
        ELSE completed_at 
    END
WHERE id = $1
`

type UpdateMatchStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchStatus, arg.ID, arg.Status)
	return err
}
