// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TournamentBracket struct {
	ID           pgtype.UUID      `json:"id"`
	TournamentID pgtype.UUID      `json:"tournament_id"`
	TotalRounds  int32            `json:"total_rounds"`
	TotalMatches int32            `json:"total_matches"`
	ByesCount    int32            `json:"byes_count"`
	GeneratedAt  time.Time        `json:"generated_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

type TournamentMatch struct {
	ID                   pgtype.UUID      `json:"id"`
	RoundID              pgtype.UUID      `json:"round_id"`
	MatchNumber          int32            `json:"match_number"`
	NextMatchID          pgtype.UUID      `json:"next_match_id"`
	Participant1ID       pgtype.UUID      `json:"participant1_id"`
	Participant2ID       pgtype.UUID      `json:"participant2_id"`
	Status               string           `json:"status"`
	Participant1Ready    bool             `json:"participant1_ready"`
	Participant2Ready    bool             `json:"participant2_ready"`
	WinnerID             pgtype.UUID      `json:"winner_id"`
	ScorePlayer1         pgtype.Int4      `json:"score_player1"`
	ScorePlayer2         pgtype.Int4      `json:"score_player2"`
	ResultSource         pgtype.Text      `json:"result_source"`
	DisconnectedPlayerID pgtype.UUID      `json:"disconnected_player_id"`
	DisconnectedAt       pgtype.Timestamp `json:"disconnected_at"`
	GameApiMatchID       pgtype.Text      `json:"game_api_match_id"`
	GameApiPollAttempts  pgtype.Int4      `json:"game_api_poll_attempts"`
	GameApiLastPoll      pgtype.Timestamp `json:"game_api_last_poll"`
	CreatedAt            time.Time        `json:"created_at"`
	StartedAt            pgtype.Timestamp `json:"started_at"`
	CompletedAt          pgtype.Timestamp `json:"completed_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
}

type TournamentRound struct {
	ID           pgtype.UUID      `json:"id"`
	BracketID    pgtype.UUID      `json:"bracket_id"`
	RoundNumber  int32            `json:"round_number"`
	RoundName    string           `json:"round_name"`
	MatchesCount int32            `json:"matches_count"`
	Status       string           `json:"status"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}
