// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/winspire-core/services/matchmaking/internal/domain"
)

type Game struct {
	ID                pgtype.UUID `json:"id"`
	GameIntegrationID pgtype.UUID `json:"game_integration_id"`
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	StoragePath       string      `json:"storage_path"`
	Version           string      `json:"version"`
	IsActive          bool        `json:"is_active"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type Prelobby struct {
	ID               pgtype.UUID      `json:"id"`
	TournamentID     pgtype.UUID      `json:"tournament_id"`
	Status           string           `json:"status"`
	GracePeriodStart pgtype.Timestamp `json:"grace_period_start"`
	GracePeriodEnd   pgtype.Timestamp `json:"grace_period_end"`
	MinParticipants  int32            `json:"min_participants"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

type PrelobbyActivityFeed struct {
	ID              pgtype.UUID `json:"id"`
	TournamentID    pgtype.UUID `json:"tournament_id"`
	EventType       string      `json:"event_type"`
	Message         string      `json:"message"`
	ParticipantName pgtype.Text `json:"participant_name"`
	CreatedAt       time.Time   `json:"created_at"`
}

type PrelobbyParticipantSnapshot struct {
	ID               pgtype.UUID             `json:"id"`
	TournamentID     pgtype.UUID             `json:"tournament_id"`
	Participants     domain.ParticipantsJSON `json:"participants"`
	ParticipantCount int32                   `json:"participant_count"`
	CreatedAt        time.Time               `json:"created_at"`
}

type TournamentBracket struct {
	ID           pgtype.UUID         `json:"id"`
	TournamentID pgtype.UUID         `json:"tournament_id"`
	GameSnapshot domain.GameSnapshot `json:"game_snapshot"`
	TotalRounds  int32               `json:"total_rounds"`
	TotalMatches int32               `json:"total_matches"`
	ByesCount    int32               `json:"byes_count"`
	GeneratedAt  time.Time           `json:"generated_at"`
	CompletedAt  pgtype.Timestamp    `json:"completed_at"`
}

type TournamentHost struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TournamentHostMember struct {
	ID        pgtype.UUID        `json:"id"`
	HostID    pgtype.UUID        `json:"host_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TournamentMatch struct {
	ID                     pgtype.UUID      `json:"id"`
	RoundID                pgtype.UUID      `json:"round_id"`
	MatchNumber            int32            `json:"match_number"`
	NextMatchID            pgtype.UUID      `json:"next_match_id"`
	Participant1ID         pgtype.UUID      `json:"participant1_id"`
	Participant2ID         pgtype.UUID      `json:"participant2_id"`
	Status                 string           `json:"status"`
	Participant1Ready      bool             `json:"participant1_ready"`
	Participant2Ready      bool             `json:"participant2_ready"`
	Participant1GameLoaded bool             `json:"participant1_game_loaded"`
	Participant2GameLoaded bool             `json:"participant2_game_loaded"`
	WinnerID               pgtype.UUID      `json:"winner_id"`
	ScorePlayer1           pgtype.Int4      `json:"score_player1"`
	ScorePlayer2           pgtype.Int4      `json:"score_player2"`
	ResultSource           pgtype.Text      `json:"result_source"`
	DisconnectedPlayerID   pgtype.UUID      `json:"disconnected_player_id"`
	DisconnectedAt         pgtype.Timestamp `json:"disconnected_at"`
	GameApiMatchID         pgtype.Text      `json:"game_api_match_id"`
	GameApiPollAttempts    pgtype.Int4      `json:"game_api_poll_attempts"`
	GameApiLastPoll        pgtype.Timestamp `json:"game_api_last_poll"`
	Version                int32            `json:"version"`
	CreatedAt              time.Time        `json:"created_at"`
	StartedAt              pgtype.Timestamp `json:"started_at"`
	CompletedAt            pgtype.Timestamp `json:"completed_at"`
	UpdatedAt              time.Time        `json:"updated_at"`
}

type TournamentRegistration struct {
	ID           pgtype.UUID        `json:"id"`
	TournamentID pgtype.UUID        `json:"tournament_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Status       string             `json:"status"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CheckedInAt  pgtype.Timestamptz `json:"checked_in_at"`
	IsReady      pgtype.Bool        `json:"is_ready"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TournamentRound struct {
	ID           pgtype.UUID      `json:"id"`
	BracketID    pgtype.UUID      `json:"bracket_id"`
	RoundNumber  int32            `json:"round_number"`
	RoundName    string           `json:"round_name"`
	MatchesCount int32            `json:"matches_count"`
	Status       string           `json:"status"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

type TournamentTournament struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	ReadyWindow              json.RawMessage    `json:"ready_window"`
	Prize                    json.RawMessage    `json:"prize"`
	GameSnapshot             json.RawMessage    `json:"game_snapshot"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}
