// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prelobby_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/winspire-core/services/matchmaking/internal/domain"
)

const AddActivityFeedEvent = `-- name: AddActivityFeedEvent :one

INSERT INTO prelobby_activity_feed (tournament_id, event_type, message, participant_name)
VALUES ($1, $2, $3, $4)
RETURNING id, tournament_id, event_type, message, participant_name, created_at
`

type AddActivityFeedEventParams struct {
	TournamentID    pgtype.UUID `json:"tournament_id"`
	EventType       string      `json:"event_type"`
	Message         string      `json:"message"`
	ParticipantName pgtype.Text `json:"participant_name"`
}

// ============================================================================
// ACTIVITY FEED QUERIES
// ============================================================================
// Adds an event to the activity feed
func (q *Queries) AddActivityFeedEvent(ctx context.Context, arg AddActivityFeedEventParams) (PrelobbyActivityFeed, error) {
	row := q.db.QueryRow(ctx, AddActivityFeedEvent,
		arg.TournamentID,
		arg.EventType,
		arg.Message,
		arg.ParticipantName,
	)
	var i PrelobbyActivityFeed
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.EventType,
		&i.Message,
		&i.ParticipantName,
		&i.CreatedAt,
	)
	return i, err
}

const CreateParticipantSnapshot = `-- name: CreateParticipantSnapshot :one

INSERT INTO prelobby_participant_snapshots (tournament_id, participants, participant_count)
VALUES ($1, $2, $3)
ON CONFLICT (tournament_id) DO UPDATE SET
    participants = EXCLUDED.participants,
    participant_count = EXCLUDED.participant_count
RETURNING id, tournament_id, participants, participant_count, created_at
`

type CreateParticipantSnapshotParams struct {
	TournamentID     pgtype.UUID             `json:"tournament_id"`
	Participants     domain.ParticipantsJSON `json:"participants"`
	ParticipantCount int32                   `json:"participant_count"`
}

// ============================================================================
// PARTICIPANT SNAPSHOT QUERIES
// ============================================================================
// Creates or updates participant snapshot when grace period ends
func (q *Queries) CreateParticipantSnapshot(ctx context.Context, arg CreateParticipantSnapshotParams) (PrelobbyParticipantSnapshot, error) {
	row := q.db.QueryRow(ctx, CreateParticipantSnapshot, arg.TournamentID, arg.Participants, arg.ParticipantCount)
	var i PrelobbyParticipantSnapshot
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Participants,
		&i.ParticipantCount,
		&i.CreatedAt,
	)
	return i, err
}

const CreatePreLobby = `-- name: CreatePreLobby :one


INSERT INTO prelobbies (tournament_id, min_participants)
VALUES ($1, $2)
RETURNING id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at
`

type CreatePreLobbyParams struct {
	TournamentID    pgtype.UUID `json:"tournament_id"`
	MinParticipants int32       `json:"min_participants"`
}

// SQLC queries for pre-lobby operations
// Feature: Tournament Pre-Lobby Backend
// ============================================================================
// PRE-LOBBY QUERIES
// ============================================================================
// Creates a new pre-lobby for a tournament
func (q *Queries) CreatePreLobby(ctx context.Context, arg CreatePreLobbyParams) (Prelobby, error) {
	row := q.db.QueryRow(ctx, CreatePreLobby, arg.TournamentID, arg.MinParticipants)
	var i Prelobby
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Status,
		&i.GracePeriodStart,
		&i.GracePeriodEnd,
		&i.MinParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteOldActivityFeedEvents = `-- name: DeleteOldActivityFeedEvents :exec
DELETE FROM prelobby_activity_feed 
WHERE tournament_id = $1 
AND created_at < NOW() - INTERVAL '24 hours'
`

// Deletes activity feed events older than a certain threshold (cleanup)
func (q *Queries) DeleteOldActivityFeedEvents(ctx context.Context, tournamentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOldActivityFeedEvents, tournamentID)
	return err
}

const DeletePreLobby = `-- name: DeletePreLobby :exec
DELETE FROM prelobbies WHERE tournament_id = $1
`

// Deletes a pre-lobby (cascades to snapshots and activity feed)
func (q *Queries) DeletePreLobby(ctx context.Context, tournamentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeletePreLobby, tournamentID)
	return err
}

const GetActiveGracePeriods = `-- name: GetActiveGracePeriods :many
SELECT id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at FROM prelobbies 
WHERE status = 'grace_period' AND grace_period_end > NOW()
`

// Gets all pre-lobbies currently in grace period (for recovery on startup)
func (q *Queries) GetActiveGracePeriods(ctx context.Context) ([]Prelobby, error) {
	rows, err := q.db.Query(ctx, GetActiveGracePeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prelobby{}
	for rows.Next() {
		var i Prelobby
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Status,
			&i.GracePeriodStart,
			&i.GracePeriodEnd,
			&i.MinParticipants,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetActivityFeedCount = `-- name: GetActivityFeedCount :one
SELECT COUNT(*) AS count FROM prelobby_activity_feed WHERE tournament_id = $1
`

// Gets total count of activity feed events for a tournament
func (q *Queries) GetActivityFeedCount(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, GetActivityFeedCount, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetParticipantSnapshot = `-- name: GetParticipantSnapshot :one
SELECT id, tournament_id, participants, participant_count, created_at FROM prelobby_participant_snapshots WHERE tournament_id = $1
`

// Gets participant snapshot for a tournament
func (q *Queries) GetParticipantSnapshot(ctx context.Context, tournamentID pgtype.UUID) (PrelobbyParticipantSnapshot, error) {
	row := q.db.QueryRow(ctx, GetParticipantSnapshot, tournamentID)
	var i PrelobbyParticipantSnapshot
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Participants,
		&i.ParticipantCount,
		&i.CreatedAt,
	)
	return i, err
}

const GetPreLobbiesByStatus = `-- name: GetPreLobbiesByStatus :many
SELECT id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at FROM prelobbies WHERE status = $1
`

// Gets all pre-lobbies with a specific status
func (q *Queries) GetPreLobbiesByStatus(ctx context.Context, status string) ([]Prelobby, error) {
	rows, err := q.db.Query(ctx, GetPreLobbiesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prelobby{}
	for rows.Next() {
		var i Prelobby
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Status,
			&i.GracePeriodStart,
			&i.GracePeriodEnd,
			&i.MinParticipants,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPreLobbyByID = `-- name: GetPreLobbyByID :one
SELECT id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at FROM prelobbies WHERE id = $1
`

// Gets pre-lobby state by pre-lobby ID
func (q *Queries) GetPreLobbyByID(ctx context.Context, id pgtype.UUID) (Prelobby, error) {
	row := q.db.QueryRow(ctx, GetPreLobbyByID, id)
	var i Prelobby
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Status,
		&i.GracePeriodStart,
		&i.GracePeriodEnd,
		&i.MinParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPreLobbyByTournament = `-- name: GetPreLobbyByTournament :one
SELECT id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at FROM prelobbies WHERE tournament_id = $1
`

// Gets pre-lobby state by tournament ID
func (q *Queries) GetPreLobbyByTournament(ctx context.Context, tournamentID pgtype.UUID) (Prelobby, error) {
	row := q.db.QueryRow(ctx, GetPreLobbyByTournament, tournamentID)
	var i Prelobby
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Status,
		&i.GracePeriodStart,
		&i.GracePeriodEnd,
		&i.MinParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRecentActivityFeed = `-- name: GetRecentActivityFeed :many
SELECT id, tournament_id, event_type, message, participant_name, created_at FROM prelobby_activity_feed 
WHERE tournament_id = $1 
ORDER BY created_at DESC 
LIMIT 20
`

// Gets the 20 most recent activity feed events for a tournament
func (q *Queries) GetRecentActivityFeed(ctx context.Context, tournamentID pgtype.UUID) ([]PrelobbyActivityFeed, error) {
	rows, err := q.db.Query(ctx, GetRecentActivityFeed, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrelobbyActivityFeed{}
	for rows.Next() {
		var i PrelobbyActivityFeed
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.EventType,
			&i.Message,
			&i.ParticipantName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ParticipantSnapshotExists = `-- name: ParticipantSnapshotExists :one
SELECT EXISTS(SELECT 1 FROM prelobby_participant_snapshots WHERE tournament_id = $1) AS exists
`

// Checks if a snapshot already exists for a tournament
func (q *Queries) ParticipantSnapshotExists(ctx context.Context, tournamentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ParticipantSnapshotExists, tournamentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const StartGracePeriod = `-- name: StartGracePeriod :one
UPDATE prelobbies 
SET status = 'grace_period', 
    grace_period_start = NOW(),
    grace_period_end = NOW() + INTERVAL '30 seconds',
    updated_at = NOW()
WHERE tournament_id = $1 AND status = 'waiting'
RETURNING id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at
`

// Transitions pre-lobby to grace_period status with 30-second window
func (q *Queries) StartGracePeriod(ctx context.Context, tournamentID pgtype.UUID) (Prelobby, error) {
	row := q.db.QueryRow(ctx, StartGracePeriod, tournamentID)
	var i Prelobby
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Status,
		&i.GracePeriodStart,
		&i.GracePeriodEnd,
		&i.MinParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdatePreLobbyStatus = `-- name: UpdatePreLobbyStatus :one
UPDATE prelobbies
SET status = $2, updated_at = NOW()
WHERE tournament_id = $1
RETURNING id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at
`

type UpdatePreLobbyStatusParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	Status       string      `json:"status"`
}

// Updates pre-lobby status
func (q *Queries) UpdatePreLobbyStatus(ctx context.Context, arg UpdatePreLobbyStatusParams) (Prelobby, error) {
	row := q.db.QueryRow(ctx, UpdatePreLobbyStatus, arg.TournamentID, arg.Status)
	var i Prelobby
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Status,
		&i.GracePeriodStart,
		&i.GracePeriodEnd,
		&i.MinParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdatePreLobbyWithParams = `-- name: UpdatePreLobbyWithParams :one
UPDATE prelobbies
SET
    status = COALESCE($1, status),
    grace_period_start = COALESCE($2, grace_period_start),
    grace_period_end = COALESCE($3, grace_period_end),
    min_participants = COALESCE($4, min_participants),
    updated_at = NOW()
WHERE tournament_id = $5
RETURNING id, tournament_id, status, grace_period_start, grace_period_end, min_participants, created_at, updated_at
`

type UpdatePreLobbyWithParamsParams struct {
	Status           pgtype.Text      `json:"status"`
	GracePeriodStart pgtype.Timestamp `json:"grace_period_start"`
	GracePeriodEnd   pgtype.Timestamp `json:"grace_period_end"`
	MinParticipants  pgtype.Int4      `json:"min_participants"`
	TournamentID     pgtype.UUID      `json:"tournament_id"`
}

// Flexible update - only updates provided (non-null) fields
func (q *Queries) UpdatePreLobbyWithParams(ctx context.Context, arg UpdatePreLobbyWithParamsParams) (Prelobby, error) {
	row := q.db.QueryRow(ctx, UpdatePreLobbyWithParams,
		arg.Status,
		arg.GracePeriodStart,
		arg.GracePeriodEnd,
		arg.MinParticipants,
		arg.TournamentID,
	)
	var i Prelobby
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Status,
		&i.GracePeriodStart,
		&i.GracePeriodEnd,
		&i.MinParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
