// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Assign winner to next match's participant slot
	AssignWinnerToNextMatch(ctx context.Context, arg AssignWinnerToNextMatchParams) error
	// Clear disconnect tracking when player reconnects
	ClearMatchDisconnect(ctx context.Context, id pgtype.UUID) error
	// ============================================================================
	// Bracket Queries
	// ============================================================================
	CreateBracket(ctx context.Context, arg CreateBracketParams) (TournamentBracket, error)
	// ============================================================================
	// Match Queries
	// ============================================================================
	CreateMatch(ctx context.Context, arg CreateMatchParams) (TournamentMatch, error)
	// ============================================================================
	// Round Queries
	// ============================================================================
	CreateRound(ctx context.Context, arg CreateRoundParams) (TournamentRound, error)
	DeleteBracket(ctx context.Context, id pgtype.UUID) error
	// Get all active rounds (in_progress status)
	GetActiveRounds(ctx context.Context) ([]GetActiveRoundsRow, error)
	GetBracketByID(ctx context.Context, id pgtype.UUID) (TournamentBracket, error)
	GetBracketByTournamentID(ctx context.Context, tournamentID pgtype.UUID) (TournamentBracket, error)
	// Complex join query for bracket visualization
	GetBracketWithRoundsAndMatches(ctx context.Context, tournamentID pgtype.UUID) ([]GetBracketWithRoundsAndMatchesRow, error)
	// Get the final match (next_match_id IS NULL)
	GetFinalMatch(ctx context.Context, tournamentID pgtype.UUID) (TournamentMatch, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (TournamentMatch, error)
	GetMatchesByRoundID(ctx context.Context, roundID pgtype.UUID) ([]TournamentMatch, error)
	// Get matches that need Game API polling
	GetMatchesForGameAPIPolling(ctx context.Context, limit int32) ([]TournamentMatch, error)
	// Get all matches for a specific player (participant1 or participant2)
	GetMatchesForPlayer(ctx context.Context, participant1ID pgtype.UUID) ([]TournamentMatch, error)
	GetRoundByBracketAndNumber(ctx context.Context, arg GetRoundByBracketAndNumberParams) (TournamentRound, error)
	GetRoundByID(ctx context.Context, id pgtype.UUID) (TournamentRound, error)
	GetRoundsByBracketID(ctx context.Context, bracketID pgtype.UUID) ([]TournamentRound, error)
	// Track player disconnect for CS:GO-style handling
	UpdateMatchDisconnect(ctx context.Context, arg UpdateMatchDisconnectParams) error
	// Track Game API polling attempts
	UpdateMatchGameAPIInfo(ctx context.Context, arg UpdateMatchGameAPIInfoParams) error
	// Update ready status for a specific participant
	UpdateMatchReady(ctx context.Context, arg UpdateMatchReadyParams) error
	UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) error
	// Update scores during match (for disconnect point adjustments)
	UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error
	UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error
}

var _ Querier = (*Queries)(nil)
