// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// ACTIVITY FEED QUERIES
	// ============================================================================
	// Adds an event to the activity feed
	AddActivityFeedEvent(ctx context.Context, arg AddActivityFeedEventParams) (PrelobbyActivityFeed, error)
	AddTournamentHostMember(ctx context.Context, arg AddTournamentHostMemberParams) (TournamentHostMember, error)
	// Assign winner to next match's participant slot
	// Handles both NULL and uuid.Nil (00000000-0000-0000-0000-000000000000) as empty slots
	// Later round matches are created with participant1_id = uuid.Nil (not NULL) as placeholder
	AssignWinnerToNextMatch(ctx context.Context, arg AssignWinnerToNextMatchParams) error
	CancelTournament(ctx context.Context, id pgtype.UUID) error
	CheckInTournamentParticipant(ctx context.Context, arg CheckInTournamentParticipantParams) error
	// Clear disconnected player info
	ClearDisconnectedPlayerInfo(ctx context.Context, id pgtype.UUID) error
	// Clear disconnect tracking when player reconnects
	ClearMatchDisconnect(ctx context.Context, id pgtype.UUID) error
	CompleteTournament(ctx context.Context, id pgtype.UUID) error
	// Counts all games including inactive
	CountAllGames(ctx context.Context) (int64, error)
	CountConfirmedTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) (int64, error)
	// Counts total active games
	CountGames(ctx context.Context) (int64, error)
	CountReadyTournamentParticipants(ctx context.Context, tournamentID pgtype.UUID) (int64, error)
	CountTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) (int64, error)
	CountTournamentRegistrationsByStatus(ctx context.Context, arg CountTournamentRegistrationsByStatusParams) (int64, error)
	// ============================================================================
	// Bracket Queries
	// ============================================================================
	CreateBracket(ctx context.Context, arg CreateBracketParams) (TournamentBracket, error)
	// ============================================================================
	// GAME QUERIES (BC: GameLibrary - merged from game-management service)
	// Generated code will be used by internal/games/repository.go
	// ============================================================================
	// Creates a new game and returns the created record
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	// ============================================================================
	// Match Queries
	// ============================================================================
	CreateMatch(ctx context.Context, arg CreateMatchParams) (TournamentMatch, error)
	// ============================================================================
	// PARTICIPANT SNAPSHOT QUERIES
	// ============================================================================
	// Creates or updates participant snapshot when grace period ends
	CreateParticipantSnapshot(ctx context.Context, arg CreateParticipantSnapshotParams) (PrelobbyParticipantSnapshot, error)
	// SQLC queries for pre-lobby operations
	// Feature: Tournament Pre-Lobby Backend
	// ============================================================================
	// PRE-LOBBY QUERIES
	// ============================================================================
	// Creates a new pre-lobby for a tournament
	CreatePreLobby(ctx context.Context, arg CreatePreLobbyParams) (Prelobby, error)
	// ============================================================================
	// Round Queries
	// ============================================================================
	CreateRound(ctx context.Context, arg CreateRoundParams) (TournamentRound, error)
	CreateTournament(ctx context.Context, arg CreateTournamentParams) (TournamentTournament, error)
	CreateTournamentHost(ctx context.Context, arg CreateTournamentHostParams) (TournamentHost, error)
	// Creates a host with a specific ID (used for personal hosts where host_id = user_id)
	CreateTournamentHostWithIDAndOwner(ctx context.Context, arg CreateTournamentHostWithIDAndOwnerParams) (CreateTournamentHostWithIDAndOwnerRow, error)
	CreateTournamentHostWithOwner(ctx context.Context, arg CreateTournamentHostWithOwnerParams) (CreateTournamentHostWithOwnerRow, error)
	// ============================================================================
	// TOURNAMENT REGISTRATION QUERIES
	// ============================================================================
	CreateTournamentRegistration(ctx context.Context, arg CreateTournamentRegistrationParams) (TournamentRegistration, error)
	DeleteBracket(ctx context.Context, id pgtype.UUID) error
	// Soft delete - sets is_active to false
	DeleteGame(ctx context.Context, id pgtype.UUID) error
	// Deletes activity feed events older than a certain threshold (cleanup)
	DeleteOldActivityFeedEvents(ctx context.Context, tournamentID pgtype.UUID) error
	// Deletes a pre-lobby (cascades to snapshots and activity feed)
	DeletePreLobby(ctx context.Context, tournamentID pgtype.UUID) error
	DeleteTournament(ctx context.Context, id pgtype.UUID) error
	DeleteTournamentRegistration(ctx context.Context, arg DeleteTournamentRegistrationParams) error
	// Find matches in 'loading' status older than specified timestamp (for timeout monitoring)
	FindLoadingMatchesOlderThan(ctx context.Context, updatedAt time.Time) ([]TournamentMatch, error)
	// Checks if a game exists
	GameExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// Checks if a slug is already taken
	GameSlugExists(ctx context.Context, slug string) (bool, error)
	// Gets all pre-lobbies currently in grace period (for recovery on startup)
	GetActiveGracePeriods(ctx context.Context) ([]Prelobby, error)
	// Get all active rounds (in_progress status)
	GetActiveRounds(ctx context.Context) ([]GetActiveRoundsRow, error)
	// Gets total count of activity feed events for a tournament
	GetActivityFeedCount(ctx context.Context, tournamentID pgtype.UUID) (int64, error)
	GetBracketByID(ctx context.Context, id pgtype.UUID) (TournamentBracket, error)
	GetBracketByTournamentID(ctx context.Context, tournamentID pgtype.UUID) (TournamentBracket, error)
	// Complex join query for bracket visualization
	GetBracketWithRoundsAndMatches(ctx context.Context, tournamentID pgtype.UUID) ([]GetBracketWithRoundsAndMatchesRow, error)
	GetConfirmedTournamentUserIDs(ctx context.Context, tournamentID pgtype.UUID) ([]pgtype.UUID, error)
	// Get the final match (next_match_id IS NULL)
	GetFinalMatch(ctx context.Context, tournamentID pgtype.UUID) (TournamentMatch, error)
	// Retrieves a game by its ID
	GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error)
	// Retrieves an active game by its game integration ID
	GetGameByIntegrationID(ctx context.Context, gameIntegrationID pgtype.UUID) (Game, error)
	// Retrieves an active game by its slug
	GetGameBySlug(ctx context.Context, slug string) (Game, error)
	// Get the latest (highest round_number) round for a tournament
	GetLatestRoundByTournamentID(ctx context.Context, tournamentID pgtype.UUID) (GetLatestRoundByTournamentIDRow, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (TournamentMatch, error)
	GetMatchesByRoundID(ctx context.Context, roundID pgtype.UUID) ([]TournamentMatch, error)
	// Get all matches for a specific tournament and round number
	GetMatchesByTournamentAndRound(ctx context.Context, arg GetMatchesByTournamentAndRoundParams) ([]TournamentMatch, error)
	// Get matches that need Game API polling
	GetMatchesForGameAPIPolling(ctx context.Context, limit int32) ([]TournamentMatch, error)
	// Get all matches for a specific player (participant1 or participant2)
	GetMatchesForPlayer(ctx context.Context, participant1ID pgtype.UUID) ([]TournamentMatch, error)
	// Gets participant snapshot for a tournament
	GetParticipantSnapshot(ctx context.Context, tournamentID pgtype.UUID) (PrelobbyParticipantSnapshot, error)
	// Gets all pre-lobbies with a specific status
	GetPreLobbiesByStatus(ctx context.Context, status string) ([]Prelobby, error)
	// Gets pre-lobby state by pre-lobby ID
	GetPreLobbyByID(ctx context.Context, id pgtype.UUID) (Prelobby, error)
	// Gets pre-lobby state by tournament ID
	GetPreLobbyByTournament(ctx context.Context, tournamentID pgtype.UUID) (Prelobby, error)
	// Gets the 20 most recent activity feed events for a tournament
	GetRecentActivityFeed(ctx context.Context, tournamentID pgtype.UUID) ([]PrelobbyActivityFeed, error)
	GetRoundByBracketAndNumber(ctx context.Context, arg GetRoundByBracketAndNumberParams) (TournamentRound, error)
	GetRoundByID(ctx context.Context, id pgtype.UUID) (TournamentRound, error)
	GetRoundsByBracketID(ctx context.Context, bracketID pgtype.UUID) ([]TournamentRound, error)
	GetTournamentByExternalID(ctx context.Context, arg GetTournamentByExternalIDParams) (TournamentTournament, error)
	GetTournamentByHostAndID(ctx context.Context, arg GetTournamentByHostAndIDParams) (TournamentTournament, error)
	// ============================================================================
	// TOURNAMENT QUERIES
	// ============================================================================
	GetTournamentByID(ctx context.Context, id pgtype.UUID) (TournamentTournament, error)
	// ============================================================================
	// TOURNAMENT SCHEMA QUERIES
	// Generated code for tournament bounded context (merged from tournament service)
	// ============================================================================
	// ============================================================================
	// HOST QUERIES
	// ============================================================================
	GetTournamentHostByID(ctx context.Context, id pgtype.UUID) (TournamentHost, error)
	GetTournamentHostMembers(ctx context.Context, hostID pgtype.UUID) ([]TournamentHostMember, error)
	GetTournamentRegistration(ctx context.Context, arg GetTournamentRegistrationParams) (TournamentRegistration, error)
	GetTournamentUserHostRole(ctx context.Context, arg GetTournamentUserHostRoleParams) (string, error)
	GetTournamentUserHosts(ctx context.Context, userID pgtype.UUID) ([]TournamentHost, error)
	GetTournamentUserHostsWithRole(ctx context.Context, userID pgtype.UUID) ([]GetTournamentUserHostsWithRoleRow, error)
	GetUserTournamentRegistrations(ctx context.Context, arg GetUserTournamentRegistrationsParams) ([]TournamentRegistration, error)
	// Hard delete - permanently removes game (use with caution)
	HardDeleteGame(ctx context.Context, id pgtype.UUID) error
	// Check if a participant has lost any match in the specified tournament
	HasParticipantLostInTournament(ctx context.Context, arg HasParticipantLostInTournamentParams) (bool, error)
	// ============================================================================
	// HOST MEMBERS QUERIES
	// ============================================================================
	IsTournamentUserHostAdmin(ctx context.Context, arg IsTournamentUserHostAdminParams) (bool, error)
	// Lists all games including inactive ones (admin use)
	ListAllGames(ctx context.Context) ([]Game, error)
	ListAllTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) ([]TournamentRegistration, error)
	ListConfirmedTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) ([]TournamentRegistration, error)
	// Lists all active games ordered by name
	ListGames(ctx context.Context) ([]Game, error)
	ListTournamentHosts(ctx context.Context, arg ListTournamentHostsParams) ([]TournamentHost, error)
	ListTournamentRegistrations(ctx context.Context, arg ListTournamentRegistrationsParams) ([]TournamentRegistration, error)
	ListTournamentsByHostID(ctx context.Context, hostID pgtype.UUID) ([]TournamentTournament, error)
	ListTournamentsByHostIDWithStatus(ctx context.Context, arg ListTournamentsByHostIDWithStatusParams) ([]TournamentTournament, error)
	ListTournamentsByStatus(ctx context.Context, dollar_1 []string) ([]TournamentTournament, error)
	// Atomically mark game loaded and return if both are now loaded
	// Uses idempotency check - only updates if player not already marked as loaded
	MarkGameLoadedAndCheckBoth(ctx context.Context, arg MarkGameLoadedAndCheckBothParams) (TournamentMatch, error)
	// Checks if a snapshot already exists for a tournament
	ParticipantSnapshotExists(ctx context.Context, tournamentID pgtype.UUID) (bool, error)
	RemoveTournamentHostMember(ctx context.Context, arg RemoveTournamentHostMemberParams) error
	SaveTournament(ctx context.Context, arg SaveTournamentParams) (TournamentTournament, error)
	// Transitions pre-lobby to grace_period status with 30-second window
	StartGracePeriod(ctx context.Context, tournamentID pgtype.UUID) (Prelobby, error)
	StartTournament(ctx context.Context, id pgtype.UUID) error
	TournamentExists(ctx context.Context, id pgtype.UUID) (bool, error)
	UpdateBracketCompletedAt(ctx context.Context, arg UpdateBracketCompletedAtParams) error
	// Update disconnected player info without changing status
	UpdateDisconnectedPlayerOnly(ctx context.Context, arg UpdateDisconnectedPlayerOnlyParams) error
	// Updates a game's information using optional parameters
	UpdateGame(ctx context.Context, arg UpdateGameParams) error
	// Track player disconnect for CS:GO-style handling
	UpdateMatchDisconnect(ctx context.Context, arg UpdateMatchDisconnectParams) error
	// Track Game API polling attempts
	UpdateMatchGameAPIInfo(ctx context.Context, arg UpdateMatchGameAPIInfoParams) error
	// Update ready status for a specific participant
	UpdateMatchReady(ctx context.Context, arg UpdateMatchReadyParams) error
	UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) error
	// Update scores during match (for disconnect point adjustments)
	UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error
	// Update match status with optimistic locking
	UpdateMatchStatusWithVersion(ctx context.Context, arg UpdateMatchStatusWithVersionParams) (TournamentMatch, error)
	// Updates pre-lobby status
	UpdatePreLobbyStatus(ctx context.Context, arg UpdatePreLobbyStatusParams) (Prelobby, error)
	// Flexible update - only updates provided (non-null) fields
	UpdatePreLobbyWithParams(ctx context.Context, arg UpdatePreLobbyWithParamsParams) (Prelobby, error)
	UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error
	UpdateTournamentHost(ctx context.Context, arg UpdateTournamentHostParams) (TournamentHost, error)
	UpdateTournamentRegistrationReady(ctx context.Context, arg UpdateTournamentRegistrationReadyParams) error
	UpdateTournamentRegistrationStatus(ctx context.Context, arg UpdateTournamentRegistrationStatusParams) error
	UpdateTournamentStatus(ctx context.Context, arg UpdateTournamentStatusParams) error
	WithdrawTournamentRegistration(ctx context.Context, arg WithdrawTournamentRegistrationParams) error
}

var _ Querier = (*Queries)(nil)
