// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRound = `-- name: CreateRound :one

INSERT INTO tournament_rounds (
    id,
    bracket_id,
    round_number,
    round_name,
    matches_count,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, bracket_id, round_number, round_name, matches_count, status, started_at, completed_at
`

type CreateRoundParams struct {
	ID           pgtype.UUID `json:"id"`
	BracketID    pgtype.UUID `json:"bracket_id"`
	RoundNumber  int32       `json:"round_number"`
	RoundName    string      `json:"round_name"`
	MatchesCount int32       `json:"matches_count"`
	Status       string      `json:"status"`
}

// ============================================================================
// Round Queries
// ============================================================================
func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, CreateRound,
		arg.ID,
		arg.BracketID,
		arg.RoundNumber,
		arg.RoundName,
		arg.MatchesCount,
		arg.Status,
	)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.BracketID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchesCount,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetActiveRounds = `-- name: GetActiveRounds :many
SELECT r.id, r.bracket_id, r.round_number, r.round_name, r.matches_count, r.status, r.started_at, r.completed_at, b.tournament_id
FROM tournament_rounds r
JOIN tournament_brackets b ON b.id = r.bracket_id
WHERE r.status = 'in_progress'
ORDER BY b.tournament_id, r.round_number
`

type GetActiveRoundsRow struct {
	ID           pgtype.UUID      `json:"id"`
	BracketID    pgtype.UUID      `json:"bracket_id"`
	RoundNumber  int32            `json:"round_number"`
	RoundName    string           `json:"round_name"`
	MatchesCount int32            `json:"matches_count"`
	Status       string           `json:"status"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
	TournamentID pgtype.UUID      `json:"tournament_id"`
}

// Get all active rounds (in_progress status)
func (q *Queries) GetActiveRounds(ctx context.Context) ([]GetActiveRoundsRow, error) {
	rows, err := q.db.Query(ctx, GetActiveRounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveRoundsRow{}
	for rows.Next() {
		var i GetActiveRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.BracketID,
			&i.RoundNumber,
			&i.RoundName,
			&i.MatchesCount,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLatestRoundByTournamentID = `-- name: GetLatestRoundByTournamentID :one
SELECT r.id, r.bracket_id, r.round_number, r.round_name, r.matches_count, r.status, r.started_at, r.completed_at, b.tournament_id
FROM tournament_rounds r
JOIN tournament_brackets b ON b.id = r.bracket_id
WHERE b.tournament_id = $1
ORDER BY r.round_number DESC
LIMIT 1
`

type GetLatestRoundByTournamentIDRow struct {
	ID           pgtype.UUID      `json:"id"`
	BracketID    pgtype.UUID      `json:"bracket_id"`
	RoundNumber  int32            `json:"round_number"`
	RoundName    string           `json:"round_name"`
	MatchesCount int32            `json:"matches_count"`
	Status       string           `json:"status"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
	TournamentID pgtype.UUID      `json:"tournament_id"`
}

// Get the latest (highest round_number) round for a tournament
func (q *Queries) GetLatestRoundByTournamentID(ctx context.Context, tournamentID pgtype.UUID) (GetLatestRoundByTournamentIDRow, error) {
	row := q.db.QueryRow(ctx, GetLatestRoundByTournamentID, tournamentID)
	var i GetLatestRoundByTournamentIDRow
	err := row.Scan(
		&i.ID,
		&i.BracketID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchesCount,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TournamentID,
	)
	return i, err
}

const GetRoundByBracketAndNumber = `-- name: GetRoundByBracketAndNumber :one
SELECT id, bracket_id, round_number, round_name, matches_count, status, started_at, completed_at FROM tournament_rounds
WHERE bracket_id = $1 AND round_number = $2
`

type GetRoundByBracketAndNumberParams struct {
	BracketID   pgtype.UUID `json:"bracket_id"`
	RoundNumber int32       `json:"round_number"`
}

func (q *Queries) GetRoundByBracketAndNumber(ctx context.Context, arg GetRoundByBracketAndNumberParams) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, GetRoundByBracketAndNumber, arg.BracketID, arg.RoundNumber)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.BracketID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchesCount,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetRoundByID = `-- name: GetRoundByID :one
SELECT id, bracket_id, round_number, round_name, matches_count, status, started_at, completed_at FROM tournament_rounds
WHERE id = $1
`

func (q *Queries) GetRoundByID(ctx context.Context, id pgtype.UUID) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, GetRoundByID, id)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.BracketID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchesCount,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetRoundsByBracketID = `-- name: GetRoundsByBracketID :many
SELECT id, bracket_id, round_number, round_name, matches_count, status, started_at, completed_at FROM tournament_rounds
WHERE bracket_id = $1
ORDER BY round_number ASC
`

func (q *Queries) GetRoundsByBracketID(ctx context.Context, bracketID pgtype.UUID) ([]TournamentRound, error) {
	rows, err := q.db.Query(ctx, GetRoundsByBracketID, bracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRound{}
	for rows.Next() {
		var i TournamentRound
		if err := rows.Scan(
			&i.ID,
			&i.BracketID,
			&i.RoundNumber,
			&i.RoundName,
			&i.MatchesCount,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRoundStatus = `-- name: UpdateRoundStatus :exec
UPDATE tournament_rounds
SET 
    status = $2,
    started_at = CASE 
        WHEN $2 = 'in_progress' AND started_at IS NULL THEN NOW() 
        ELSE started_at 
    END,
    completed_at = CASE 
        WHEN $2 = 'completed' THEN NOW() 
        ELSE completed_at 
    END
WHERE id = $1
`

type UpdateRoundStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateRoundStatus, arg.ID, arg.Status)
	return err
}
