// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournament_queries.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddTournamentHostMember = `-- name: AddTournamentHostMember :one
INSERT INTO tournament.host_members (host_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (host_id, user_id) DO UPDATE
SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, host_id, user_id, role, created_at, updated_at
`

type AddTournamentHostMemberParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddTournamentHostMember(ctx context.Context, arg AddTournamentHostMemberParams) (TournamentHostMember, error) {
	row := q.db.QueryRow(ctx, AddTournamentHostMember, arg.HostID, arg.UserID, arg.Role)
	var i TournamentHostMember
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CancelTournament = `-- name: CancelTournament :exec
UPDATE tournament.tournaments
SET
    status = 'cancelled',
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, CancelTournament, id)
	return err
}

const CheckInTournamentParticipant = `-- name: CheckInTournamentParticipant :exec
UPDATE tournament.registrations
SET
    status = 'checked_in',
    checked_in_at = NOW(),
    is_ready = true,
    updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $2
`

type CheckInTournamentParticipantParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckInTournamentParticipant(ctx context.Context, arg CheckInTournamentParticipantParams) error {
	_, err := q.db.Exec(ctx, CheckInTournamentParticipant, arg.TournamentID, arg.UserID)
	return err
}

const CompleteTournament = `-- name: CompleteTournament :exec
UPDATE tournament.tournaments
SET
    status = 'completed',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, CompleteTournament, id)
	return err
}

const CountConfirmedTournamentRegistrations = `-- name: CountConfirmedTournamentRegistrations :one
SELECT COUNT(*) AS count
FROM tournament.registrations
WHERE tournament_id = $1 AND status IN ('confirmed', 'checked_in')
`

func (q *Queries) CountConfirmedTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountConfirmedTournamentRegistrations, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountReadyTournamentParticipants = `-- name: CountReadyTournamentParticipants :one
SELECT COUNT(*) AS count
FROM tournament.registrations
WHERE tournament_id = $1 AND is_ready = true
`

func (q *Queries) CountReadyTournamentParticipants(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountReadyTournamentParticipants, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTournamentRegistrations = `-- name: CountTournamentRegistrations :one
SELECT COUNT(*) AS count
FROM tournament.registrations
WHERE tournament_id = $1
`

func (q *Queries) CountTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountTournamentRegistrations, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTournamentRegistrationsByStatus = `-- name: CountTournamentRegistrationsByStatus :one
SELECT COUNT(*) AS count
FROM tournament.registrations
WHERE tournament_id = $1 AND status = $2
`

type CountTournamentRegistrationsByStatusParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	Status       string      `json:"status"`
}

func (q *Queries) CountTournamentRegistrationsByStatus(ctx context.Context, arg CountTournamentRegistrationsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountTournamentRegistrationsByStatus, arg.TournamentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateTournament = `-- name: CreateTournament :one
INSERT INTO tournament.tournaments (
    host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id, game_snapshot
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
`

type CreateTournamentParams struct {
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	GameSnapshot             json.RawMessage    `json:"game_snapshot"`
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (TournamentTournament, error) {
	row := q.db.QueryRow(ctx, CreateTournament,
		arg.HostID,
		arg.Name,
		arg.Description,
		arg.ExternalID,
		arg.Status,
		arg.ScheduledStartTimeAt,
		arg.RegistrationWindowOpenAt,
		arg.MinimumTeamCount,
		arg.MaximumTeamCount,
		arg.TeamSize,
		arg.AutoForceReady,
		arg.GameID,
		arg.SpaceID,
		arg.TemplateID,
		arg.GameSnapshot,
	)
	var i TournamentTournament
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.GameSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateTournamentHost = `-- name: CreateTournamentHost :one
INSERT INTO tournament.hosts (name, description, logo_url, website_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, logo_url, website_url, created_at, updated_at
`

type CreateTournamentHostParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
}

func (q *Queries) CreateTournamentHost(ctx context.Context, arg CreateTournamentHostParams) (TournamentHost, error) {
	row := q.db.QueryRow(ctx, CreateTournamentHost,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i TournamentHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateTournamentHostWithIDAndOwner = `-- name: CreateTournamentHostWithIDAndOwner :one
WITH new_host AS (
    INSERT INTO tournament.hosts (id, name, description, logo_url, website_url)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, name, description, logo_url, website_url, created_at, updated_at
),
new_member AS (
    INSERT INTO tournament.host_members (host_id, user_id, role)
    SELECT id, $6, 'owner'
    FROM new_host
    RETURNING id
)
SELECT id, name, description, logo_url, website_url, created_at, updated_at FROM new_host
`

type CreateTournamentHostWithIDAndOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
	UserID      pgtype.UUID `json:"user_id"`
}

type CreateTournamentHostWithIDAndOwnerRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Creates a host with a specific ID (used for personal hosts where host_id = user_id)
func (q *Queries) CreateTournamentHostWithIDAndOwner(ctx context.Context, arg CreateTournamentHostWithIDAndOwnerParams) (CreateTournamentHostWithIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, CreateTournamentHostWithIDAndOwner,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.UserID,
	)
	var i CreateTournamentHostWithIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateTournamentHostWithOwner = `-- name: CreateTournamentHostWithOwner :one
WITH new_host AS (
    INSERT INTO tournament.hosts (name, description, logo_url, website_url)
    VALUES ($1, $2, $3, $4)
    RETURNING id, name, description, logo_url, website_url, created_at, updated_at
),
new_member AS (
    INSERT INTO tournament.host_members (host_id, user_id, role)
    SELECT id, $5, 'owner'
    FROM new_host
    RETURNING id
)
SELECT id, name, description, logo_url, website_url, created_at, updated_at FROM new_host
`

type CreateTournamentHostWithOwnerParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
	UserID      pgtype.UUID `json:"user_id"`
}

type CreateTournamentHostWithOwnerRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTournamentHostWithOwner(ctx context.Context, arg CreateTournamentHostWithOwnerParams) (CreateTournamentHostWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, CreateTournamentHostWithOwner,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.UserID,
	)
	var i CreateTournamentHostWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateTournamentRegistration = `-- name: CreateTournamentRegistration :one

INSERT INTO tournament.registrations (
    tournament_id, user_id, team_id,
    status, display_name, avatar_url
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tournament_id, user_id) DO UPDATE
SET
    status = EXCLUDED.status,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
`

type CreateTournamentRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
	TeamID       pgtype.UUID `json:"team_id"`
	Status       string      `json:"status"`
	DisplayName  string      `json:"display_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
}

// ============================================================================
// TOURNAMENT REGISTRATION QUERIES
// ============================================================================
func (q *Queries) CreateTournamentRegistration(ctx context.Context, arg CreateTournamentRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, CreateTournamentRegistration,
		arg.TournamentID,
		arg.UserID,
		arg.TeamID,
		arg.Status,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CheckedInAt,
		&i.IsReady,
		&i.RegisteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteTournament = `-- name: DeleteTournament :exec
DELETE FROM tournament.tournaments
WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteTournament, id)
	return err
}

const DeleteTournamentRegistration = `-- name: DeleteTournamentRegistration :exec
DELETE FROM tournament.registrations
WHERE tournament_id = $1 AND user_id = $2
`

type DeleteTournamentRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTournamentRegistration(ctx context.Context, arg DeleteTournamentRegistrationParams) error {
	_, err := q.db.Exec(ctx, DeleteTournamentRegistration, arg.TournamentID, arg.UserID)
	return err
}

const GetConfirmedTournamentUserIDs = `-- name: GetConfirmedTournamentUserIDs :many
SELECT user_id
FROM tournament.registrations
WHERE tournament_id = $1 AND status IN ('confirmed', 'checked_in')
ORDER BY registered_at ASC
`

func (q *Queries) GetConfirmedTournamentUserIDs(ctx context.Context, tournamentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, GetConfirmedTournamentUserIDs, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTournamentByExternalID = `-- name: GetTournamentByExternalID :one
SELECT
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
FROM tournament.tournaments
WHERE external_id = $1 AND host_id = $2
`

type GetTournamentByExternalIDParams struct {
	ExternalID pgtype.Text `json:"external_id"`
	HostID     pgtype.UUID `json:"host_id"`
}

func (q *Queries) GetTournamentByExternalID(ctx context.Context, arg GetTournamentByExternalIDParams) (TournamentTournament, error) {
	row := q.db.QueryRow(ctx, GetTournamentByExternalID, arg.ExternalID, arg.HostID)
	var i TournamentTournament
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.GameSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTournamentByHostAndID = `-- name: GetTournamentByHostAndID :one
SELECT
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
FROM tournament.tournaments
WHERE host_id = $1 AND id = $2
`

type GetTournamentByHostAndIDParams struct {
	HostID pgtype.UUID `json:"host_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetTournamentByHostAndID(ctx context.Context, arg GetTournamentByHostAndIDParams) (TournamentTournament, error) {
	row := q.db.QueryRow(ctx, GetTournamentByHostAndID, arg.HostID, arg.ID)
	var i TournamentTournament
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.GameSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTournamentByID = `-- name: GetTournamentByID :one

SELECT
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
FROM tournament.tournaments
WHERE id = $1
`

// ============================================================================
// TOURNAMENT QUERIES
// ============================================================================
func (q *Queries) GetTournamentByID(ctx context.Context, id pgtype.UUID) (TournamentTournament, error) {
	row := q.db.QueryRow(ctx, GetTournamentByID, id)
	var i TournamentTournament
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.GameSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTournamentHostByID = `-- name: GetTournamentHostByID :one


SELECT id, name, description, logo_url, website_url, created_at, updated_at
FROM tournament.hosts
WHERE id = $1
`

// ============================================================================
// TOURNAMENT SCHEMA QUERIES
// Generated code for tournament bounded context (merged from tournament service)
// ============================================================================
// ============================================================================
// HOST QUERIES
// ============================================================================
func (q *Queries) GetTournamentHostByID(ctx context.Context, id pgtype.UUID) (TournamentHost, error) {
	row := q.db.QueryRow(ctx, GetTournamentHostByID, id)
	var i TournamentHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTournamentHostMembers = `-- name: GetTournamentHostMembers :many
SELECT id, host_id, user_id, role, created_at, updated_at
FROM tournament.host_members
WHERE host_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTournamentHostMembers(ctx context.Context, hostID pgtype.UUID) ([]TournamentHostMember, error) {
	rows, err := q.db.Query(ctx, GetTournamentHostMembers, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentHostMember{}
	for rows.Next() {
		var i TournamentHostMember
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTournamentRegistration = `-- name: GetTournamentRegistration :one
SELECT
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament.registrations
WHERE tournament_id = $1 AND user_id = $2
`

type GetTournamentRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTournamentRegistration(ctx context.Context, arg GetTournamentRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, GetTournamentRegistration, arg.TournamentID, arg.UserID)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CheckedInAt,
		&i.IsReady,
		&i.RegisteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTournamentUserHostRole = `-- name: GetTournamentUserHostRole :one
SELECT role
FROM tournament.host_members
WHERE host_id = $1 AND user_id = $2
`

type GetTournamentUserHostRoleParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTournamentUserHostRole(ctx context.Context, arg GetTournamentUserHostRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, GetTournamentUserHostRole, arg.HostID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const GetTournamentUserHosts = `-- name: GetTournamentUserHosts :many
SELECT h.id, h.name, h.description, h.logo_url, h.website_url, h.created_at, h.updated_at
FROM tournament.hosts h
INNER JOIN tournament.host_members hm ON h.id = hm.host_id
WHERE hm.user_id = $1
ORDER BY h.created_at DESC
`

func (q *Queries) GetTournamentUserHosts(ctx context.Context, userID pgtype.UUID) ([]TournamentHost, error) {
	rows, err := q.db.Query(ctx, GetTournamentUserHosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentHost{}
	for rows.Next() {
		var i TournamentHost
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTournamentUserHostsWithRole = `-- name: GetTournamentUserHostsWithRole :many
SELECT
    h.id,
    h.name,
    h.description,
    h.logo_url,
    h.website_url,
    h.created_at,
    h.updated_at,
    hm.role as member_role
FROM tournament.hosts h
INNER JOIN tournament.host_members hm ON h.id = hm.host_id
WHERE hm.user_id = $1
ORDER BY h.created_at DESC
`

type GetTournamentUserHostsWithRoleRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberRole  string             `json:"member_role"`
}

func (q *Queries) GetTournamentUserHostsWithRole(ctx context.Context, userID pgtype.UUID) ([]GetTournamentUserHostsWithRoleRow, error) {
	rows, err := q.db.Query(ctx, GetTournamentUserHostsWithRole, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTournamentUserHostsWithRoleRow{}
	for rows.Next() {
		var i GetTournamentUserHostsWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserTournamentRegistrations = `-- name: GetUserTournamentRegistrations :many
SELECT
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament.registrations
WHERE user_id = $1
ORDER BY registered_at DESC
LIMIT $2 OFFSET $3
`

type GetUserTournamentRegistrationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetUserTournamentRegistrations(ctx context.Context, arg GetUserTournamentRegistrationsParams) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, GetUserTournamentRegistrations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CheckedInAt,
			&i.IsReady,
			&i.RegisteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IsTournamentUserHostAdmin = `-- name: IsTournamentUserHostAdmin :one

SELECT EXISTS(
    SELECT 1 FROM tournament.host_members
    WHERE host_id = $1
    AND user_id = $2
    AND role IN ('admin', 'owner')
) AS is_admin
`

type IsTournamentUserHostAdminParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// ============================================================================
// HOST MEMBERS QUERIES
// ============================================================================
func (q *Queries) IsTournamentUserHostAdmin(ctx context.Context, arg IsTournamentUserHostAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, IsTournamentUserHostAdmin, arg.HostID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const ListAllTournamentRegistrations = `-- name: ListAllTournamentRegistrations :many
SELECT
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament.registrations
WHERE tournament_id = $1
ORDER BY registered_at ASC
`

func (q *Queries) ListAllTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, ListAllTournamentRegistrations, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CheckedInAt,
			&i.IsReady,
			&i.RegisteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListConfirmedTournamentRegistrations = `-- name: ListConfirmedTournamentRegistrations :many
SELECT
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament.registrations
WHERE tournament_id = $1 AND status IN ('confirmed', 'checked_in')
ORDER BY registered_at ASC
`

func (q *Queries) ListConfirmedTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, ListConfirmedTournamentRegistrations, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CheckedInAt,
			&i.IsReady,
			&i.RegisteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTournamentHosts = `-- name: ListTournamentHosts :many
SELECT id, name, description, logo_url, website_url, created_at, updated_at
FROM tournament.hosts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTournamentHostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTournamentHosts(ctx context.Context, arg ListTournamentHostsParams) ([]TournamentHost, error) {
	rows, err := q.db.Query(ctx, ListTournamentHosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentHost{}
	for rows.Next() {
		var i TournamentHost
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTournamentRegistrations = `-- name: ListTournamentRegistrations :many
SELECT
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament.registrations
WHERE tournament_id = $1
ORDER BY registered_at DESC
LIMIT $2 OFFSET $3
`

type ListTournamentRegistrationsParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListTournamentRegistrations(ctx context.Context, arg ListTournamentRegistrationsParams) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, ListTournamentRegistrations, arg.TournamentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CheckedInAt,
			&i.IsReady,
			&i.RegisteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTournamentsByHostID = `-- name: ListTournamentsByHostID :many
SELECT
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
FROM tournament.tournaments
WHERE host_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTournamentsByHostID(ctx context.Context, hostID pgtype.UUID) ([]TournamentTournament, error) {
	rows, err := q.db.Query(ctx, ListTournamentsByHostID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentTournament{}
	for rows.Next() {
		var i TournamentTournament
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ScheduledStartTimeAt,
			&i.RegistrationWindowOpenAt,
			&i.ActualStartTimeAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.MinimumTeamCount,
			&i.MaximumTeamCount,
			&i.TeamSize,
			&i.AutoForceReady,
			&i.GameID,
			&i.SpaceID,
			&i.TemplateID,
			&i.ReadyWindow,
			&i.Prize,
			&i.GameSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTournamentsByHostIDWithStatus = `-- name: ListTournamentsByHostIDWithStatus :many
SELECT
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
FROM tournament.tournaments
WHERE host_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListTournamentsByHostIDWithStatusParams struct {
	HostID pgtype.UUID `json:"host_id"`
	Status string      `json:"status"`
}

func (q *Queries) ListTournamentsByHostIDWithStatus(ctx context.Context, arg ListTournamentsByHostIDWithStatusParams) ([]TournamentTournament, error) {
	rows, err := q.db.Query(ctx, ListTournamentsByHostIDWithStatus, arg.HostID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentTournament{}
	for rows.Next() {
		var i TournamentTournament
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ScheduledStartTimeAt,
			&i.RegistrationWindowOpenAt,
			&i.ActualStartTimeAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.MinimumTeamCount,
			&i.MaximumTeamCount,
			&i.TeamSize,
			&i.AutoForceReady,
			&i.GameID,
			&i.SpaceID,
			&i.TemplateID,
			&i.ReadyWindow,
			&i.Prize,
			&i.GameSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTournamentsByStatus = `-- name: ListTournamentsByStatus :many
SELECT
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
FROM tournament.tournaments
WHERE status = ANY($1::text[])
ORDER BY scheduled_start_time_at ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListTournamentsByStatus(ctx context.Context, dollar_1 []string) ([]TournamentTournament, error) {
	rows, err := q.db.Query(ctx, ListTournamentsByStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentTournament{}
	for rows.Next() {
		var i TournamentTournament
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ScheduledStartTimeAt,
			&i.RegistrationWindowOpenAt,
			&i.ActualStartTimeAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.MinimumTeamCount,
			&i.MaximumTeamCount,
			&i.TeamSize,
			&i.AutoForceReady,
			&i.GameID,
			&i.SpaceID,
			&i.TemplateID,
			&i.ReadyWindow,
			&i.Prize,
			&i.GameSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveTournamentHostMember = `-- name: RemoveTournamentHostMember :exec
DELETE FROM tournament.host_members
WHERE host_id = $1 AND user_id = $2
`

type RemoveTournamentHostMemberParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTournamentHostMember(ctx context.Context, arg RemoveTournamentHostMemberParams) error {
	_, err := q.db.Exec(ctx, RemoveTournamentHostMember, arg.HostID, arg.UserID)
	return err
}

const SaveTournament = `-- name: SaveTournament :one
UPDATE tournament.tournaments
SET
    name = $2,
    description = $3,
    status = $4,
    scheduled_start_time_at = $5,
    actual_start_time_at = $6,
    completed_at = $7,
    cancelled_at = $8,
    minimum_team_count = $9,
    maximum_team_count = $10,
    ready_window = $11,
    prize = $12,
    game_snapshot = $13,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize, game_snapshot,
    created_at, updated_at
`

type SaveTournamentParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	Status               string             `json:"status"`
	ScheduledStartTimeAt pgtype.Timestamptz `json:"scheduled_start_time_at"`
	ActualStartTimeAt    pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount     pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount     pgtype.Int4        `json:"maximum_team_count"`
	ReadyWindow          json.RawMessage    `json:"ready_window"`
	Prize                json.RawMessage    `json:"prize"`
	GameSnapshot         json.RawMessage    `json:"game_snapshot"`
}

func (q *Queries) SaveTournament(ctx context.Context, arg SaveTournamentParams) (TournamentTournament, error) {
	row := q.db.QueryRow(ctx, SaveTournament,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ScheduledStartTimeAt,
		arg.ActualStartTimeAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.MinimumTeamCount,
		arg.MaximumTeamCount,
		arg.ReadyWindow,
		arg.Prize,
		arg.GameSnapshot,
	)
	var i TournamentTournament
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.GameSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const StartTournament = `-- name: StartTournament :exec
UPDATE tournament.tournaments
SET
    status = 'started',
    actual_start_time_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) StartTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, StartTournament, id)
	return err
}

const TournamentExists = `-- name: TournamentExists :one
SELECT EXISTS(
    SELECT 1 FROM tournament.tournaments WHERE id = $1
) AS exists
`

func (q *Queries) TournamentExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, TournamentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UpdateTournamentHost = `-- name: UpdateTournamentHost :one
UPDATE tournament.hosts
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    logo_url = COALESCE($4, logo_url),
    website_url = COALESCE($5, website_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, logo_url, website_url, created_at, updated_at
`

type UpdateTournamentHostParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
}

func (q *Queries) UpdateTournamentHost(ctx context.Context, arg UpdateTournamentHostParams) (TournamentHost, error) {
	row := q.db.QueryRow(ctx, UpdateTournamentHost,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i TournamentHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateTournamentRegistrationReady = `-- name: UpdateTournamentRegistrationReady :exec
UPDATE tournament.registrations
SET is_ready = $3, updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $2
`

type UpdateTournamentRegistrationReadyParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
	IsReady      pgtype.Bool `json:"is_ready"`
}

func (q *Queries) UpdateTournamentRegistrationReady(ctx context.Context, arg UpdateTournamentRegistrationReadyParams) error {
	_, err := q.db.Exec(ctx, UpdateTournamentRegistrationReady, arg.TournamentID, arg.UserID, arg.IsReady)
	return err
}

const UpdateTournamentRegistrationStatus = `-- name: UpdateTournamentRegistrationStatus :exec
UPDATE tournament.registrations
SET status = $3, updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $2
`

type UpdateTournamentRegistrationStatusParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateTournamentRegistrationStatus(ctx context.Context, arg UpdateTournamentRegistrationStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateTournamentRegistrationStatus, arg.TournamentID, arg.UserID, arg.Status)
	return err
}

const UpdateTournamentStatus = `-- name: UpdateTournamentStatus :exec
UPDATE tournament.tournaments
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTournamentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateTournamentStatus(ctx context.Context, arg UpdateTournamentStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateTournamentStatus, arg.ID, arg.Status)
	return err
}

const WithdrawTournamentRegistration = `-- name: WithdrawTournamentRegistration :exec
UPDATE tournament.registrations
SET
    status = 'withdrawn',
    is_ready = false,
    updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $2
`

type WithdrawTournamentRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) WithdrawTournamentRegistration(ctx context.Context, arg WithdrawTournamentRegistrationParams) error {
	_, err := q.db.Exec(ctx, WithdrawTournamentRegistration, arg.TournamentID, arg.UserID)
	return err
}
