services:
  # We use supabase for postgres in development
  # postgres:
  #   image: postgres:17-alpine
  #   container_name: tournament-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: competition_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  tournament:
    build:
      context: .
      dockerfile: cmd/tournament/Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8089:8089"
    environment:
      - APP_ENV=development
      - SERVICE_PORT=8089
      - POSTGRES_DSN=postgresql://postgres:postgres@127.0.0.1:54322/postgres?sslmode=disable

      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: tournament-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:

  redis_data:



