services:
  # We use supabase for postgres in development
  # postgres:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: competition_host
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  competition-host-stream:
    build:
      context: ../..
      dockerfile: services/competition-host-stream/cmd/competition-host-stream/Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "8086:8086"
    environment:
      - APP_ENV=development
      - SERVICE_PORT=8086
      - POSTGRES_DSN=postgresql://postgres:postgres@host.docker.internal:54322/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
  redis:
    image: redis:8.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  pgdata: {}


