version: '3.8'

services:
  mini-admin:
    build:
      context: .
      dockerfile: cmd/mini-admin/Dockerfile.dev
    ports:
      - "8088:8088"
    env_file:
      - .env
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    depends_on:

volumes:
  go-mod-cache:
  go-build-cache:

