-- No custom tables needed - we rely entirely on Supabase's built-in structures:
-- - auth.users: User accounts and authentication
-- - auth.identities: OAuth provider links (automatic and manual linking)
-- - Password reset tokens: Handled internally by Supabase
-- - Sessions: JWT-based, stateless (no table needed)
--
-- See: https://supabase.com/docs/guides/auth/auth-identity-linking
--
-- For now, we use Supabase's user_metadata for role storage.
-- Custom RBAC tables can be added later if needed.
