// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Organizations or individuals that can host tournaments
type Host struct {
	// Unique identifier for the host
	ID pgtype.UUID `json:"id"`
	// Display name of the host organization
	Name string `json:"name"`
	// Optional description of the host
	Description pgtype.Text `json:"description"`
	// URL to host logo/avatar
	LogoUrl pgtype.Text `json:"logo_url"`
	// Host website URL
	WebsiteUrl pgtype.Text        `json:"website_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// User permissions and roles for hosts
type HostMember struct {
	ID pgtype.UUID `json:"id"`
	// Reference to the host
	HostID pgtype.UUID `json:"host_id"`
	// Reference to user (from auth system)
	UserID pgtype.UUID `json:"user_id"`
	// User role: owner, admin, or member
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Tournaments hosted by organizations
type Tournament struct {
	// Unique identifier for the tournament
	ID pgtype.UUID `json:"id"`
	// Reference to the host organization
	HostID pgtype.UUID `json:"host_id"`
	// Display name of the tournament
	Name string `json:"name"`
	// Optional description
	Description pgtype.Text `json:"description"`
	// External identifier for idempotency
	ExternalID pgtype.Text `json:"external_id"`
	// Current tournament status
	Status string `json:"status"`
	// When the tournament is scheduled to start
	ScheduledStartTimeAt pgtype.Timestamptz `json:"scheduled_start_time_at"`
	// When registration opens
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	// When the tournament actually started
	ActualStartTimeAt pgtype.Timestamptz `json:"actual_start_time_at"`
	// When the tournament was completed
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	// When the tournament was cancelled
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	// Minimum number of teams required to start
	MinimumTeamCount pgtype.Int4 `json:"minimum_team_count"`
	// Maximum number of teams allowed
	MaximumTeamCount pgtype.Int4 `json:"maximum_team_count"`
	// Number of players per team
	TeamSize int32 `json:"team_size"`
	// Whether to automatically force ready status
	AutoForceReady pgtype.Bool `json:"auto_force_ready"`
	// Optional reference to the game
	GameID pgtype.UUID `json:"game_id"`
	// Optional reference to the space
	SpaceID pgtype.UUID `json:"space_id"`
	// Optional reference to a tournament template
	TemplateID pgtype.UUID        `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// JSONB configuration for tournament ready/check-in window
	ReadyWindow []byte `json:"ready_window"`
	// JSONB configuration for tournament prize structure
	Prize []byte `json:"prize"`
}

// Participant registrations for tournaments
type TournamentRegistration struct {
	// Unique identifier for the registration
	ID pgtype.UUID `json:"id"`
	// Reference to the tournament
	TournamentID pgtype.UUID `json:"tournament_id"`
	// Reference to the registered user
	UserID pgtype.UUID `json:"user_id"`
	// Optional reference to a team (for team tournaments)
	TeamID pgtype.UUID `json:"team_id"`
	// Registration status: pending (initial), registered (took a spot), confirmed (manually confirmed), checked_in (checked in before tournament), withdrawn (left tournament), disqualified (removed by host)
	Status string `json:"status"`
	// Participant display name (cached from user profile)
	DisplayName string `json:"display_name"`
	// Participant avatar URL (cached from user profile)
	AvatarUrl pgtype.Text `json:"avatar_url"`
	// When the participant checked in
	CheckedInAt pgtype.Timestamptz `json:"checked_in_at"`
	// Whether the participant has confirmed ready status
	IsReady pgtype.Bool `json:"is_ready"`
	// When the participant registered
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
