// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHostMember = `-- name: AddHostMember :one
INSERT INTO host_members (host_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (host_id, user_id) DO UPDATE
SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, host_id, user_id, role, created_at, updated_at
`

type AddHostMemberParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

// Adds a user to a host with a specified role
func (q *Queries) AddHostMember(ctx context.Context, arg AddHostMemberParams) (HostMember, error) {
	row := q.db.QueryRow(ctx, addHostMember, arg.HostID, arg.UserID, arg.Role)
	var i HostMember
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelTournament = `-- name: CancelTournament :exec
UPDATE tournaments
SET 
    status = 'cancelled',
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// Marks tournament as cancelled
func (q *Queries) CancelTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelTournament, id)
	return err
}

const checkInParticipant = `-- name: CheckInParticipant :exec
UPDATE tournament_registrations
SET 
    status = 'checked_in',
    checked_in_at = NOW(),
    is_ready = true,
    updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $2
`

type CheckInParticipantParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Marks participant as checked in
func (q *Queries) CheckInParticipant(ctx context.Context, arg CheckInParticipantParams) error {
	_, err := q.db.Exec(ctx, checkInParticipant, arg.TournamentID, arg.UserID)
	return err
}

const completeTournament = `-- name: CompleteTournament :exec
UPDATE tournaments
SET 
    status = 'completed',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// Marks tournament as completed
func (q *Queries) CompleteTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeTournament, id)
	return err
}

const countReadyParticipants = `-- name: CountReadyParticipants :one
SELECT COUNT(*) AS count
FROM tournament_registrations
WHERE tournament_id = $1 AND is_ready = true
`

// Counts participants who are ready
func (q *Queries) CountReadyParticipants(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReadyParticipants, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTournamentRegistrations = `-- name: CountTournamentRegistrations :one
SELECT COUNT(*) AS count
FROM tournament_registrations
WHERE tournament_id = $1
`

// Counts total registrations for a tournament
func (q *Queries) CountTournamentRegistrations(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTournamentRegistrations, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTournamentRegistrationsByStatus = `-- name: CountTournamentRegistrationsByStatus :one
SELECT COUNT(*) AS count
FROM tournament_registrations
WHERE tournament_id = $1 AND status = $2
`

type CountTournamentRegistrationsByStatusParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	Status       string      `json:"status"`
}

// Counts registrations by status
func (q *Queries) CountTournamentRegistrationsByStatus(ctx context.Context, arg CountTournamentRegistrationsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTournamentRegistrationsByStatus, arg.TournamentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (id, name, description, logo_url, website_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, logo_url, website_url, created_at, updated_at
`

type CreateHostParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
}

// Creates a new host and returns the created record
func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHostWithOwner = `-- name: CreateHostWithOwner :one
WITH new_host AS (
    INSERT INTO hosts (id, name, description, logo_url, website_url)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, name, description, logo_url, website_url, created_at, updated_at
),
new_member AS (
    INSERT INTO host_members (host_id, user_id, role)
    SELECT id, $6, 'owner'
    FROM new_host
    RETURNING id
)
SELECT id, name, description, logo_url, website_url, created_at, updated_at FROM new_host
`

type CreateHostWithOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
	UserID      pgtype.UUID `json:"user_id"`
}

type CreateHostWithOwnerRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Creates a host and adds the creator as owner in a single transaction
// Note: This must be called within a transaction (pgx.Tx)
func (q *Queries) CreateHostWithOwner(ctx context.Context, arg CreateHostWithOwnerParams) (CreateHostWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, createHostWithOwner,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.UserID,
	)
	var i CreateHostWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (
    host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize,
    created_at, updated_at
`

type CreateTournamentParams struct {
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
}

type CreateTournamentRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	ReadyWindow              []byte             `json:"ready_window"`
	Prize                    []byte             `json:"prize"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Creates a new tournament
func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (CreateTournamentRow, error) {
	row := q.db.QueryRow(ctx, createTournament,
		arg.HostID,
		arg.Name,
		arg.Description,
		arg.ExternalID,
		arg.Status,
		arg.ScheduledStartTimeAt,
		arg.RegistrationWindowOpenAt,
		arg.MinimumTeamCount,
		arg.MaximumTeamCount,
		arg.TeamSize,
		arg.AutoForceReady,
		arg.GameID,
		arg.SpaceID,
		arg.TemplateID,
	)
	var i CreateTournamentRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTournamentRegistration = `-- name: CreateTournamentRegistration :one

INSERT INTO tournament_registrations (
    tournament_id, user_id, team_id,
    status, display_name, avatar_url
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tournament_id, user_id) DO UPDATE
SET 
    status = EXCLUDED.status,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING 
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
`

type CreateTournamentRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
	TeamID       pgtype.UUID `json:"team_id"`
	Status       string      `json:"status"`
	DisplayName  string      `json:"display_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
}

// ============================================================================
// TOURNAMENT REGISTRATION QUERIES
// Scalable participant management for tournaments (10K+ participants)
// ============================================================================
// Registers a user for a tournament
func (q *Queries) CreateTournamentRegistration(ctx context.Context, arg CreateTournamentRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, createTournamentRegistration,
		arg.TournamentID,
		arg.UserID,
		arg.TeamID,
		arg.Status,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CheckedInAt,
		&i.IsReady,
		&i.RegisteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHost = `-- name: DeleteHost :exec
DELETE FROM hosts
WHERE id = $1
`

// Deletes a host (cascades to host_members due to FK constraint)
func (q *Queries) DeleteHost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHost, id)
	return err
}

const deleteRegistration = `-- name: DeleteRegistration :exec
DELETE FROM tournament_registrations
WHERE tournament_id = $1 AND user_id = $2
`

type DeleteRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Deletes a registration (hard delete)
func (q *Queries) DeleteRegistration(ctx context.Context, arg DeleteRegistrationParams) error {
	_, err := q.db.Exec(ctx, deleteRegistration, arg.TournamentID, arg.UserID)
	return err
}

const deleteTournament = `-- name: DeleteTournament :exec
DELETE FROM tournaments
WHERE id = $1
`

// Deletes a tournament
func (q *Queries) DeleteTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTournament, id)
	return err
}

const getHostByID = `-- name: GetHostByID :one

SELECT id, name, description, logo_url, website_url, created_at, updated_at
FROM hosts
WHERE id = $1
`

// ============================================================================
// HOST QUERIES
// Generated code will be used by internal/repository/host.go
// ============================================================================
// Retrieves a host by its ID
func (q *Queries) GetHostByID(ctx context.Context, id pgtype.UUID) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostMembers = `-- name: GetHostMembers :many
SELECT hm.id, hm.host_id, hm.user_id, hm.role, hm.created_at, hm.updated_at
FROM host_members hm
WHERE hm.host_id = $1
ORDER BY hm.created_at DESC
`

// Lists all members of a host
func (q *Queries) GetHostMembers(ctx context.Context, hostID pgtype.UUID) ([]HostMember, error) {
	rows, err := q.db.Query(ctx, getHostMembers, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostMember{}
	for rows.Next() {
		var i HostMember
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentByExternalID = `-- name: GetTournamentByExternalID :one
SELECT 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    created_at, updated_at
FROM tournaments
WHERE external_id = $1 AND host_id = $2
`

type GetTournamentByExternalIDParams struct {
	ExternalID pgtype.Text `json:"external_id"`
	HostID     pgtype.UUID `json:"host_id"`
}

type GetTournamentByExternalIDRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Retrieves a tournament by external ID for idempotency
func (q *Queries) GetTournamentByExternalID(ctx context.Context, arg GetTournamentByExternalIDParams) (GetTournamentByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getTournamentByExternalID, arg.ExternalID, arg.HostID)
	var i GetTournamentByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentByHostAndID = `-- name: GetTournamentByHostAndID :one
SELECT 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize,
    created_at, updated_at
FROM tournaments
WHERE host_id = $1 AND id = $2
`

type GetTournamentByHostAndIDParams struct {
	HostID pgtype.UUID `json:"host_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetTournamentByHostAndIDRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	ReadyWindow              []byte             `json:"ready_window"`
	Prize                    []byte             `json:"prize"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Retrieves a tournament scoped to a host
func (q *Queries) GetTournamentByHostAndID(ctx context.Context, arg GetTournamentByHostAndIDParams) (GetTournamentByHostAndIDRow, error) {
	row := q.db.QueryRow(ctx, getTournamentByHostAndID, arg.HostID, arg.ID)
	var i GetTournamentByHostAndIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentByID = `-- name: GetTournamentByID :one

SELECT 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize,
    created_at, updated_at
FROM tournaments
WHERE id = $1
`

type GetTournamentByIDRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	ReadyWindow              []byte             `json:"ready_window"`
	Prize                    []byte             `json:"prize"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// TOURNAMENT QUERIES
// Generated code will be used by internal/repository/tournament.go
// ============================================================================
// Retrieves a tournament by its ID
func (q *Queries) GetTournamentByID(ctx context.Context, id pgtype.UUID) (GetTournamentByIDRow, error) {
	row := q.db.QueryRow(ctx, getTournamentByID, id)
	var i GetTournamentByIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentRegistration = `-- name: GetTournamentRegistration :one
SELECT 
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament_registrations
WHERE tournament_id = $1 AND user_id = $2
`

type GetTournamentRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Gets a specific registration
func (q *Queries) GetTournamentRegistration(ctx context.Context, arg GetTournamentRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, getTournamentRegistration, arg.TournamentID, arg.UserID)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CheckedInAt,
		&i.IsReady,
		&i.RegisteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserHostRole = `-- name: GetUserHostRole :one
SELECT role
FROM host_members
WHERE host_id = $1 AND user_id = $2
`

type GetUserHostRoleParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Gets the user's role for a specific host
func (q *Queries) GetUserHostRole(ctx context.Context, arg GetUserHostRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserHostRole, arg.HostID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserHosts = `-- name: GetUserHosts :many
SELECT h.id, h.name, h.description, h.logo_url, h.website_url, h.created_at, h.updated_at
FROM hosts h
INNER JOIN host_members hm ON h.id = hm.host_id
WHERE hm.user_id = $1
ORDER BY h.created_at DESC
`

// Returns all hosts where the user is a member
func (q *Queries) GetUserHosts(ctx context.Context, userID pgtype.UUID) ([]Host, error) {
	rows, err := q.db.Query(ctx, getUserHosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserHostsWithRole = `-- name: GetUserHostsWithRole :many
SELECT 
    h.id, 
    h.name, 
    h.description, 
    h.logo_url, 
    h.website_url, 
    h.created_at, 
    h.updated_at,
    hm.role as member_role
FROM hosts h
INNER JOIN host_members hm ON h.id = hm.host_id
WHERE hm.user_id = $1
ORDER BY h.created_at DESC
`

type GetUserHostsWithRoleRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberRole  string             `json:"member_role"`
}

// Returns all hosts where the user is a member, including their role
func (q *Queries) GetUserHostsWithRole(ctx context.Context, userID pgtype.UUID) ([]GetUserHostsWithRoleRow, error) {
	rows, err := q.db.Query(ctx, getUserHostsWithRole, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserHostsWithRoleRow{}
	for rows.Next() {
		var i GetUserHostsWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTournamentRegistrations = `-- name: GetUserTournamentRegistrations :many
SELECT 
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament_registrations
WHERE user_id = $1
ORDER BY registered_at DESC
LIMIT $2 OFFSET $3
`

type GetUserTournamentRegistrationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Gets all tournaments a user is registered in
func (q *Queries) GetUserTournamentRegistrations(ctx context.Context, arg GetUserTournamentRegistrationsParams) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, getUserTournamentRegistrations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CheckedInAt,
			&i.IsReady,
			&i.RegisteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hostExists = `-- name: HostExists :one
SELECT EXISTS(
    SELECT 1 FROM hosts WHERE id = $1
) AS exists
`

// Checks if a host exists
func (q *Queries) HostExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hostExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserHostAdmin = `-- name: IsUserHostAdmin :one

SELECT EXISTS(
    SELECT 1 FROM host_members
    WHERE host_id = $1
    AND user_id = $2
    AND role IN ('admin', 'owner')
) AS is_admin
`

type IsUserHostAdminParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// ============================================================================
// HOST MEMBERS QUERIES
// ============================================================================
// Checks if a user is an admin/owner of the specified host
func (q *Queries) IsUserHostAdmin(ctx context.Context, arg IsUserHostAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserHostAdmin, arg.HostID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, name, description, logo_url, website_url, created_at, updated_at
FROM hosts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListHostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lists all hosts (optionally paginated)
func (q *Queries) ListHosts(ctx context.Context, arg ListHostsParams) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentRegistrations = `-- name: ListTournamentRegistrations :many
SELECT 
    id, tournament_id, user_id, team_id,
    status, display_name, avatar_url,
    checked_in_at, is_ready,
    registered_at, updated_at
FROM tournament_registrations
WHERE tournament_id = $1
ORDER BY registered_at DESC
LIMIT $2 OFFSET $3
`

type ListTournamentRegistrationsParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

// Lists registrations for a tournament (paginated, newest first)
func (q *Queries) ListTournamentRegistrations(ctx context.Context, arg ListTournamentRegistrationsParams) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, listTournamentRegistrations, arg.TournamentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CheckedInAt,
			&i.IsReady,
			&i.RegisteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentsByHostID = `-- name: ListTournamentsByHostID :many
SELECT 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    created_at, updated_at
FROM tournaments
WHERE host_id = $1
ORDER BY created_at DESC
`

type ListTournamentsByHostIDRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Lists all tournaments for a specific host
func (q *Queries) ListTournamentsByHostID(ctx context.Context, hostID pgtype.UUID) ([]ListTournamentsByHostIDRow, error) {
	rows, err := q.db.Query(ctx, listTournamentsByHostID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentsByHostIDRow{}
	for rows.Next() {
		var i ListTournamentsByHostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ScheduledStartTimeAt,
			&i.RegistrationWindowOpenAt,
			&i.ActualStartTimeAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.MinimumTeamCount,
			&i.MaximumTeamCount,
			&i.TeamSize,
			&i.AutoForceReady,
			&i.GameID,
			&i.SpaceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentsByHostIDWithStatus = `-- name: ListTournamentsByHostIDWithStatus :many
SELECT 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    created_at, updated_at
FROM tournaments
WHERE host_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListTournamentsByHostIDWithStatusParams struct {
	HostID pgtype.UUID `json:"host_id"`
	Status string      `json:"status"`
}

type ListTournamentsByHostIDWithStatusRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Lists tournaments for a host filtered by status
func (q *Queries) ListTournamentsByHostIDWithStatus(ctx context.Context, arg ListTournamentsByHostIDWithStatusParams) ([]ListTournamentsByHostIDWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listTournamentsByHostIDWithStatus, arg.HostID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentsByHostIDWithStatusRow{}
	for rows.Next() {
		var i ListTournamentsByHostIDWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ScheduledStartTimeAt,
			&i.RegistrationWindowOpenAt,
			&i.ActualStartTimeAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.MinimumTeamCount,
			&i.MaximumTeamCount,
			&i.TeamSize,
			&i.AutoForceReady,
			&i.GameID,
			&i.SpaceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeHostMember = `-- name: RemoveHostMember :exec
DELETE FROM host_members
WHERE host_id = $1 AND user_id = $2
`

type RemoveHostMemberParams struct {
	HostID pgtype.UUID `json:"host_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Removes a user from a host
func (q *Queries) RemoveHostMember(ctx context.Context, arg RemoveHostMemberParams) error {
	_, err := q.db.Exec(ctx, removeHostMember, arg.HostID, arg.UserID)
	return err
}

const saveTournament = `-- name: SaveTournament :one
UPDATE tournaments
SET 
    name = $2,
    description = $3,
    status = $4,
    scheduled_start_time_at = $5,
    actual_start_time_at = $6,
    completed_at = $7,
    cancelled_at = $8,
    minimum_team_count = $9,
    maximum_team_count = $10,
    ready_window = $11,
    prize = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    ready_window, prize,
    created_at, updated_at
`

type SaveTournamentParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	Status               string             `json:"status"`
	ScheduledStartTimeAt pgtype.Timestamptz `json:"scheduled_start_time_at"`
	ActualStartTimeAt    pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount     pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount     pgtype.Int4        `json:"maximum_team_count"`
	ReadyWindow          []byte             `json:"ready_window"`
	Prize                []byte             `json:"prize"`
}

type SaveTournamentRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	ReadyWindow              []byte             `json:"ready_window"`
	Prize                    []byte             `json:"prize"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Saves the full tournament aggregate state (DDD pattern)
// Used after applying aggregate business methods
func (q *Queries) SaveTournament(ctx context.Context, arg SaveTournamentParams) (SaveTournamentRow, error) {
	row := q.db.QueryRow(ctx, saveTournament,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ScheduledStartTimeAt,
		arg.ActualStartTimeAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.MinimumTeamCount,
		arg.MaximumTeamCount,
		arg.ReadyWindow,
		arg.Prize,
	)
	var i SaveTournamentRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.ReadyWindow,
		&i.Prize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startTournament = `-- name: StartTournament :exec
UPDATE tournaments
SET 
    status = 'started',
    actual_start_time_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// Marks tournament as started
func (q *Queries) StartTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startTournament, id)
	return err
}

const tournamentExists = `-- name: TournamentExists :one
SELECT EXISTS(
    SELECT 1 FROM tournaments WHERE id = $1
) AS exists
`

// Checks if a tournament exists
func (q *Queries) TournamentExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tournamentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateHost = `-- name: UpdateHost :one
UPDATE hosts
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    logo_url = COALESCE($4, logo_url),
    website_url = COALESCE($5, website_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, logo_url, website_url, created_at, updated_at
`

type UpdateHostParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
}

// Updates a host's information
func (q *Queries) UpdateHost(ctx context.Context, arg UpdateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, updateHost,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRegistrationReady = `-- name: UpdateRegistrationReady :exec
UPDATE tournament_registrations
SET is_ready = $2, updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $3
`

type UpdateRegistrationReadyParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	IsReady      pgtype.Bool `json:"is_ready"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Updates ready status
func (q *Queries) UpdateRegistrationReady(ctx context.Context, arg UpdateRegistrationReadyParams) error {
	_, err := q.db.Exec(ctx, updateRegistrationReady, arg.TournamentID, arg.IsReady, arg.UserID)
	return err
}

const updateRegistrationStatus = `-- name: UpdateRegistrationStatus :exec
UPDATE tournament_registrations
SET status = $2, updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $3
`

type UpdateRegistrationStatusParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	Status       string      `json:"status"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Updates registration status
func (q *Queries) UpdateRegistrationStatus(ctx context.Context, arg UpdateRegistrationStatusParams) error {
	_, err := q.db.Exec(ctx, updateRegistrationStatus, arg.TournamentID, arg.Status, arg.UserID)
	return err
}

const updateTournament = `-- name: UpdateTournament :one
UPDATE tournaments
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    scheduled_start_time_at = COALESCE($4, scheduled_start_time_at),
    minimum_team_count = COALESCE($5, minimum_team_count),
    maximum_team_count = COALESCE($6, maximum_team_count),
    updated_at = NOW()
WHERE id = $1
RETURNING 
    id, host_id, name, description, external_id,
    status, scheduled_start_time_at, registration_window_open_at,
    actual_start_time_at, completed_at, cancelled_at,
    minimum_team_count, maximum_team_count, team_size, auto_force_ready,
    game_id, space_id, template_id,
    created_at, updated_at
`

type UpdateTournamentParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 pgtype.Text        `json:"name"`
	Description          pgtype.Text        `json:"description"`
	ScheduledStartTimeAt pgtype.Timestamptz `json:"scheduled_start_time_at"`
	MinimumTeamCount     pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount     pgtype.Int4        `json:"maximum_team_count"`
}

type UpdateTournamentRow struct {
	ID                       pgtype.UUID        `json:"id"`
	HostID                   pgtype.UUID        `json:"host_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	ExternalID               pgtype.Text        `json:"external_id"`
	Status                   string             `json:"status"`
	ScheduledStartTimeAt     pgtype.Timestamptz `json:"scheduled_start_time_at"`
	RegistrationWindowOpenAt pgtype.Timestamptz `json:"registration_window_open_at"`
	ActualStartTimeAt        pgtype.Timestamptz `json:"actual_start_time_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	MinimumTeamCount         pgtype.Int4        `json:"minimum_team_count"`
	MaximumTeamCount         pgtype.Int4        `json:"maximum_team_count"`
	TeamSize                 int32              `json:"team_size"`
	AutoForceReady           pgtype.Bool        `json:"auto_force_ready"`
	GameID                   pgtype.UUID        `json:"game_id"`
	SpaceID                  pgtype.UUID        `json:"space_id"`
	TemplateID               pgtype.UUID        `json:"template_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Updates tournament information with optional fields
// Deprecated: Use SaveTournament for DDD aggregate persistence
func (q *Queries) UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (UpdateTournamentRow, error) {
	row := q.db.QueryRow(ctx, updateTournament,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ScheduledStartTimeAt,
		arg.MinimumTeamCount,
		arg.MaximumTeamCount,
	)
	var i UpdateTournamentRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ScheduledStartTimeAt,
		&i.RegistrationWindowOpenAt,
		&i.ActualStartTimeAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.MinimumTeamCount,
		&i.MaximumTeamCount,
		&i.TeamSize,
		&i.AutoForceReady,
		&i.GameID,
		&i.SpaceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTournamentStatus = `-- name: UpdateTournamentStatus :exec
UPDATE tournaments
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTournamentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Updates tournament status
func (q *Queries) UpdateTournamentStatus(ctx context.Context, arg UpdateTournamentStatusParams) error {
	_, err := q.db.Exec(ctx, updateTournamentStatus, arg.ID, arg.Status)
	return err
}

const withdrawRegistration = `-- name: WithdrawRegistration :exec
UPDATE tournament_registrations
SET 
    status = 'withdrawn',
    is_ready = false,
    updated_at = NOW()
WHERE tournament_id = $1 AND user_id = $2
`

type WithdrawRegistrationParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Withdraws a registration
func (q *Queries) WithdrawRegistration(ctx context.Context, arg WithdrawRegistrationParams) error {
	_, err := q.db.Exec(ctx, withdrawRegistration, arg.TournamentID, arg.UserID)
	return err
}
